/* ============================================================================
 * Data model — TypeScript mirror of the Python aba_all.py spec.
 * Every type used in the renderer, BOM generator, DXF exporter, and API.
 * No React, no DOM references — pure logic types so the file is reusable on
 * the backend (transpile to JSON Schema or generate Pydantic models from it).
 * ========================================================================== */

export type ISO = string;

export type Domain = 'electrical' | 'plumbing' | 'civil' | 'hvac' | 'generic';

/* ---------- Items / boards ---------- */

export interface Subject {
  id: string;
  tenantId: string;
  name: string;
  createdAt: ISO;
}

export interface Project {
  id: string;
  tenantId: string;
  subjectId: string;
  name: string;
  parentProjectId?: string;
  budgetTotal?: number;
  files: ProjectFile[];
  createdAt: ISO;
}

export interface ProjectFile {
  key: string;
  name: string;
  size: number;
  uploadedAt: ISO;
}

export interface Item {
  id: string;
  tenantId: string;
  title: string;
  description?: string;
  subjectId: string | null;
  projectId: string | null;
  type: 'quick_board' | 'sample' | 'parsed-spec' | 'ai_generated' | 'offline_generated';
  status: 'Draft' | 'Submitted' | 'Approved' | 'Revised' | 'Issued';
  version: number;
  revisions: Revision[];
  spec: SpecAny | null;
  scene: Scene;
  ds: DesignSheet;
  bom: { lines: BomLine[]; autoGenerated?: boolean; lastGen?: ISO };
  linkedTasks: TaskRef[];
  attachments: Attachment[];
  createdBy: string;
  createdAt: ISO;
  updatedAt: ISO;
  deletedAt?: ISO;
}

export interface Revision {
  at: ISO;
  by: string;
  snapshot: string; // base64 deflated JSON
}

export interface DesignSheet {
  type?: string;
  params: { key: string; value: string | number }[];
  sop: string[];
  approvedBy?: string;
  approvedAt?: ISO;
}

export interface TaskRef {
  taskId: string;
  module: string;
}

export interface Attachment {
  key: string;
  name: string;
  size: number;
}

/* ---------- Scene (rendered drawing) ---------- */

export interface Scene {
  w: number;
  h: number;
  bg: SceneBg;
  objects: SceneObject[];
}

export type SceneBg =
  | { type: 'grid'; grid: number }
  | { type: 'image'; imageKey: string }
  | { type: 'color'; color: string };

export type Layer = 'background' | 'symbols' | 'annotations';

export type SceneObject =
  | RectObj
  | LineObj
  | EllipseObj
  | TextObj
  | SymbolObj
  | ImageObj
  | FreehandObj
  | DimensionObj;

export interface RectObj    { id: string; kind: 'rect';     layer: Layer; x: number; y: number; w: number; h: number; fill?: string; stroke?: string; width?: number; }
export interface LineObj    { id: string; kind: 'line';     layer: Layer; x1: number; y1: number; x2: number; y2: number; stroke: string; width: number; }
export interface EllipseObj { id: string; kind: 'ellipse';  layer: Layer; x: number; y: number; w: number; h: number; fill?: string; stroke?: string; width?: number; }
export interface TextObj    { id: string; kind: 'text';     layer: Layer; x: number; y: number; text: string; size: number; color: string; bold?: boolean; }
export interface SymbolObj  { id: string; kind: 'symbol';   layer: Layer; x: number; y: number; w: number; h: number; rot: number; svg: string; name: string; assetId?: string; }
export interface ImageObj {
  id: string;
  kind: 'img';
  layer: Layer;
  x: number;
  y: number;
  w: number;
  h: number;
  src: string;
  name: string;
  rot?: number;
  opacity?: number;
  aspectLocked?: boolean;
  locked?: boolean;
  mirrorX?: boolean;
  mirrorY?: boolean;
  crop?: { x: number; y: number; w: number; h: number };
  calibratedUnitsPerPixel?: number;
}
export interface FreehandObj{ id: string; kind: 'freehand'; layer: Layer; x: number; y: number; points: [number, number][]; stroke: string; width: number; }
export interface DimensionObj { id: string; kind: 'dimension'; layer: Layer; x1: number; y1: number; x2: number; y2: number; unit: 'mm' | 'm' | 'cm'; }

/* ---------- Specs ---------- */

export type SpecAny =
  | PlumbingSpec
  | PlanSpec
  | CabinetSpecV1
  | CabinetSpecV2;

export interface PlumbingSpec {
  type: 'plumbing';
  nodes: PlumbNode[];
  edges: PlumbEdge[];
}

export interface PlumbNode {
  id: string;
  sym: string;
  x: number;
  y: number;
  label?: string;
}

export interface PlumbEdge {
  from: string;
  to: string;
  size?: string;
}

export interface PlanSpec {
  type: 'plan';
  rooms: Room[];
}

export interface Room {
  id: string;
  label: string;
  x: number;
  y: number;
  w: number;
  h: number;
  features?: { sym: string; label?: string }[];
}

export interface CabinetSpecV1 {
  type?: 'cabinet';
  rails: RailV1[];
}

export interface RailV1 {
  label: string;
  items: { sym: string; label?: string }[];
  wire?: string;
}

export interface CabinetSpecV2 {
  specType: 'cabinet';
  specVersion: 2;
  title: string;
  subtitle?: string;
  cabinet: CabinetMeta;
  sections: Section[];
  legend?: LegendEntry[];
  notes?: string;
}

export interface CabinetMeta {
  widthMm: number;
  heightMm: number;
  depthMm: number;
  enclosureType?: 'IP54' | 'IP55' | 'IP65' | 'IP66' | 'IP67' | 'IP68';
  manufacturer?: string;
  partNo?: string;
}

export interface Section {
  id: string;
  label: string;
  type: 'power' | 'control' | 'terminals';
  color: string;
  rails: Rail[];
}

export interface Rail {
  id: string;
  label: string;
  wireSize?: string;
  railType: 'DIN' | 'G' | 'busbar';
  bus?: boolean;
  busPhases?: string[];
  items: DeviceV2[];
}

export interface DeviceV2 {
  id: string;
  sym: string;
  assetId?: string;
  kind: DeviceKind;
  label: string;
  ref: string;
  rating?: string;
  poles?: number;
  cableTag?: string;
  wireColorSet?: '3P+N' | '3P' | 'DC' | '1P';
  voltage?: string;
  manufacturer?: string;
  partNo?: string;
  positionIndex?: number;
  status?: 'on' | 'off' | 'fault';
  meta?: Record<string, unknown>;
}

export type DeviceKind =
  | 'breaker'
  | 'mccb'
  | 'rcbo'
  | 'contactor'
  | 'overload'
  | 'vfd'
  | 'plc'
  | 'smps'
  | 'transformer'
  | 'terminal'
  | 'busbar'
  | 'relay'
  | 'meter'
  | 'ct'
  | 'other';

export interface LegendEntry {
  sym: string;
  label: string;
}

/* ---------- BOM ---------- */

export interface BomLine {
  key: string;
  kind: DeviceKind | 'cable' | 'misc';
  sym?: string;
  description: string;
  rating?: string;
  poles?: number;
  manufacturer?: string;
  partNo?: string;
  qty: number;
  refs: string[];
  refsText?: string;
  unitPrice?: number;
  total?: number;
  sectionBreakdown?: string;
}

/* ---------- Assets (DB-backed library) ---------- */

export interface Asset {
  id: string;
  tenantId: string;
  kind: 'symbol' | 'image';
  domain: Domain;
  name: string;
  description?: string;
  svg?: string;
  rasterKey?: string;
  category?: string;
  tags?: string[];
  standard?: string;
  meta?: Record<string, unknown>;
  createdAt: ISO;
  createdBy?: string;
}


/* ============================================================================
 * 3D + Wizard extensions (layer 2)
 * ========================================================================== */

export type WizardQuestionType = 'select' | 'number' | 'boolean' | 'text';

export interface WizardQuestion {
  id: string;
  type: WizardQuestionType;
  label: string;
  required?: boolean;
  options?: { value: string | number; label: string }[];
  min?: number;
  max?: number;
  default?: string | number | boolean;
}

export interface WizardAnswers {
  [questionId: string]: string | number | boolean;
}

export interface Asset3D extends Asset {
  assetKind: 'symbol_2d' | 'component_3d' | 'composite';
  gltfKey?: string;
  params?: Record<string, string | number | boolean>;
  dimWMm?: number;
  dimHMm?: number;
  dimDMm?: number;
  priceUnit?: number;
  priceCurrency?: string;
}

export interface Transform3D {
  x: number; y: number; z: number;
  rx?: number; ry?: number; rz?: number;
  sx?: number; sy?: number; sz?: number;
}

export interface Scene3DNode {
  id: string;
  assetId?: string | null;
  primitive?: 'box' | 'cylinder' | 'sphere' | 'line';
  color?: string;
  transform: Transform3D;
  metadata?: Record<string, unknown>;
}

export interface Scene3D {
  nodes: Scene3DNode[];
  bbox?: [number, number, number, number, number, number];
}
