/* Generate a BOM line-list from a CabinetSpec v2 by grouping devices on
 * (kind|sym|rating|poles|manufacturer|partNo).
 * Mirrors the Python aba_all.py BOM aggregator.
 */
import type { CabinetSpecV2, BomLine, DeviceV2 } from '../data-model';

const KIND_ORDER: Record<string, number> = {
  mccb: 1, breaker: 2, rcbo: 3, contactor: 4, overload: 5,
  vfd: 6, relay: 7, plc: 8, smps: 9, transformer: 10,
  meter: 11, ct: 12, terminal: 13, busbar: 14, other: 99
};

function descriptionFor(dev: DeviceV2): string {
  const sym = dev.sym || 'Device';
  return dev.rating ? `${sym} – ${dev.rating}` : sym;
}

export function generateBomFromCabSpec(spec: CabinetSpecV2): { lines: BomLine[]; autoGenerated: true; lastGen: string; source: 'cabinet-v2' } {
  const map = new Map<string, BomLine>();

  (spec.sections || []).forEach(sec => {
    (sec.rails || []).forEach(rail => {
      if (rail.bus) {
        (rail.busPhases || ['L1', 'L2', 'L3', 'N', 'PE']).forEach(ph => {
          const key = `busbar|${ph}|${rail.wireSize || ''}`;
          let line = map.get(key);
          if (!line) {
            line = { key, kind: 'busbar', sym: 'Busbar', description: `Copper busbar — ${ph}${rail.wireSize ? ` · ${rail.wireSize}` : ''}`, rating: rail.wireSize, qty: 0, refs: [] };
            map.set(key, line);
          }
          line.qty += 1;
        });
        return;
      }
      (rail.items || []).forEach(dev => {
        const key = [dev.kind || '', dev.sym || '', dev.rating || '', dev.poles ?? '', dev.manufacturer || '', dev.partNo || ''].join('|');
        let line = map.get(key);
        if (!line) {
          line = {
            key,
            kind: dev.kind || 'other',
            sym: dev.sym,
            description: descriptionFor(dev),
            rating: dev.rating,
            poles: dev.poles,
            manufacturer: dev.manufacturer,
            partNo: dev.partNo,
            qty: 0,
            refs: []
          };
          map.set(key, line);
        }
        line.qty += 1;
        if (dev.ref) line.refs.push(dev.ref);
      });
    });
  });

  const lines = Array.from(map.values()).map(line => {
    line.refs.sort();
    line.refsText = line.refs.join(', ');
    return line;
  });

  lines.sort((a, b) => (KIND_ORDER[a.kind] || 99) - (KIND_ORDER[b.kind] || 99) || (a.description || '').localeCompare(b.description || ''));

  return { lines, autoGenerated: true, lastGen: new Date().toISOString(), source: 'cabinet-v2' };
}
