// Master data — every screen defined in one compact DSL. Consumed by
// build-docx.js and build-html.js so the two output paths stay in sync.
//
// DSL nodes (arrays):
//   ['h1', text]
//   ['h2', text]
//   ['h3', text]
//   ['p',  text]
//   ['ul', [ 'item1', 'item2', ... ]]
//   ['fl', [ 'label:value', ... ]]                // field list
//   ['code', text]                                // one-line accent-code
//   ['flow', [ 'Step 1', 'Step 2', ... ]]         // arrow-separated
//   ['tbl', headers, rows, widthsPct?]            // table with header row
//   ['note', label, text]                         // callout
//
// A screen has { n, docId, title, subtitle, sections: [nodes] }.
module.exports = (function(){

const INDEX = [
  ['0',  'Purchasing Home',                        ['Purchasing Mission Control','Purchasing Calendar','My Tasks','Notifications','AI Assistant (Nexi)']],
  ['1',  'Purchase Requests',                      ['New Purchase Request','Purchase Request Details','Draft Requests','Submitted Requests','Pending Approval','Approved Requests','Rejected Requests','Cancelled Requests','Archived Requests']],
  ['2',  'AI Validation',                          ['AI Review','Duplicate Detection','Budget Verification','Consumption Analysis','Suggested Alternatives','Risk Analysis']],
  ['3',  'SOS Inventory Integration',              ['Current Stock','Available Stock','Incoming Deliveries','Reserved Inventory','Warehouse Transfer Suggestions','Internal Availability','Previous Purchase History']],
  ['4',  'Technical Specifications',               ['Product Specification','Brand Requirements','Drawing Viewer','Attachments','Technical Approval','Revision History']],
  ['5',  'Supplier Management',                    ['Supplier Directory','Supplier Profile','Supplier Qualification','Supplier Categories','Supplier Performance','Blacklisted Suppliers','Preferred Suppliers','New Supplier Registration']],
  ['6',  'Supplier Discovery',                     ['AI Supplier Search','Local Suppliers','International Suppliers','Manufacturer Search','Distributor Search','Supplier Comparison']],
  ['7',  'RFQ Center',                             ['Create RFQ','RFQ Wizard','Send RFQ','RFQ Tracking','Supplier Responses','RFQ Expiration']],
  ['8',  'Communication Center',                   ['Email','SMS','Communication Timeline','Attachments','AI Summary','Follow-up Scheduler']],
  ['9',  'Quotation Management',                   ['Quotation Inbox','AI Extraction','Price Comparison','Technical Comparison','Commercial Comparison','Currency Conversion','Landed Cost']],
  ['10', 'Negotiation',                            ['Negotiation Workspace','Counter Offers','Price History','AI Negotiation Suggestions','Supplier Commitments']],
  ['11', 'Evaluation',                             ['Supplier Scorecard','Risk Score','Quality History','Delivery Performance','Financial Stability','AI Recommendation']],
  ['12', 'Approval Center',                        ['Approval Queue','Approval Details','Multi-Level Approval','Digital Signature','Audit Log']],
  ['13', 'Purchase Orders',                        ['Create PO','Draft PO','Approved PO','Sent PO','Supplier Confirmation','Amendment History']],
  ['14', 'Receiving',                              ['Expected Deliveries','Goods Receiving','Partial Deliveries','Quality Inspection','Variance Management','Close Purchase Order']],
  ['15', 'Supplier Evaluation',                    ['Delivery Rating','Quality Rating','Service Rating','Price Rating','Overall Supplier Score']],
  ['16', 'Reports & Analytics',                    ['Spend Analysis','Supplier Analysis','Savings Report','Budget vs Actual','Procurement KPI Dashboard','Executive Reports']],
  ['17', 'Administration',                         ['Purchasing Settings','Approval Matrix','User Roles','Permissions','Email Templates','SMS Templates','AI Configuration','Integration Settings','Security & Audit']],
];

// Screen 001 — Purchasing Mission Control (already delivered separately;
// re-transcribed here at the authoritative doc-id ACC-PUR-001)
const S001 = { n:'001', docId:'ACC-PUR-001', title:'Purchasing Mission Control',
  subtitle:'Operational control center — 5-second comprehension, no scroll',
  sections:[
    ['h1','Purpose'],
    ['p','First screen displayed when a user enters Accounting → Purchasing. Operational control center for the Purchasing Department. A trained user must comprehend the entire purchasing operation within 5 seconds. No vertical scroll on a 27" monitor. Critical information only.'],
    ['h1','Access matrix'],
    ['tbl',['Role','Access'],[
      ['Purchasing Officer','Full'],['Purchasing Manager','Full'],['Accounting Manager','Full'],
      ['Finance Manager','Read only'],['CEO','Read only'],
      ['Warehouse','Limited (deliveries + receiving alerts only)'],
      ['Department Requester','No access'],
    ],[40,60]],
    ['h1','Header (80 px)'],
    ['p','Left-to-right: Company logo · breadcrumb (Accounting → Purchasing → Mission Control) · current user · current date · notifications bell · AI status indicator · global search · profile menu.'],
    ['h1','Left navigation'],
    ['ul',['Dashboard','Purchase Requests','Suppliers','RFQs','Quotations','Negotiations','Purchase Orders','Receiving','Reports','Administration']],
    ['h1','Main dashboard layout'],
    ['p','12-column responsive grid. Three rows. Nothing below the fold on a 27" monitor at 100% zoom.'],
    ['h2','Row 1 — KPI cards (5)'],
    ['tbl',['#','Card','Displays','Click target'],[
      ['1','Purchase Requests','New · Pending · Approved · Rejected · Urgent','Opens screen 1.x with matching status filter'],
      ['2','RFQs','Open · Sent · Waiting · Expired','Opens 7.4 RFQ Tracking, pre-filtered'],
      ['3','Supplier Responses','Unread · Today · Late · Urgent','Opens 7.5 Supplier Responses'],
      ['4','Purchase Orders','Draft · Approved · Issued · Receiving · Closed','Opens 13.x'],
      ['5','Budget Status','Monthly · Committed · Available · Forecast','Opens 16.4 Budget vs Actual'],
    ],[6,22,40,32]],
    ['h2','Row 2 — Priority queue + activity timeline'],
    ['h3','Left panel · AI Priority Queue'],
    ['p','Top 20 purchasing tasks requiring attention, ranked by Nexi. Columns: Priority · Request Number · Supplier · Issue · Due Date · AI Recommendation. Row actions: Review · Approve · Assign.'],
    ['h3','Right panel · Purchasing Activity Timeline'],
    ['p','Reverse-chronological. Icons per event type: Created Request · Supplier Replied · PO Approved · Shipment Delayed · Goods Received · Invoice Received · Supplier Warning. Every item click-through to source.'],
    ['h2','Row 3 — Performance · budget · alerts'],
    ['tbl',['Panel','Contents'],[
      ['Supplier Performance (left)','Top suppliers · Avg delivery · Avg quality · Response time · Risk score · Trend (30/90 days)'],
      ['Budget Utilization (middle)','Monthly · Department · Project spend · Remaining · Graph (stacked bar per month)'],
      ['Alerts (right)','Late supplier · Budget exceeded · No supplier found · Duplicate request · Approval waiting · Delivery delay · Critical inventory'],
    ],[30,70]],
    ['h1','Floating AI panel (Nexi)'],
    ['p','Always visible, bottom-right. Persistent across navigation inside Purchasing.'],
    ['ul',['Find supplier','Compare quotes','Create RFQ','Generate PO draft','Summarize supplier emails','Risk analysis','Open chat']],
    ['h1','Universal search'],
    ['p','Single input, keyboard shortcut "/". Searchable entities:'],
    ['ul',['Item','Supplier','Purchase Request','Purchase Order','RFQ','Invoice reference','SOS item code','Barcode','QR']],
    ['h1','Filters (dashboard-wide)'],
    ['ul',['Project','Department','Supplier','Category','Priority','Status','Warehouse','Date range','Budget code']],
    ['p','Filters persist per user session and are echoed in the URL for shareable links.'],
    ['h1','Live updates'],
    ['p','WebSocket subscription. Widgets update in under 2 seconds. Manual refresh not required. If the socket drops, a "reconnecting…" chip appears and the dashboard falls back to a 15-second polling interval.'],
    ['h1','Notifications'],
    ['ul',['Approval required','Supplier reply','Price change','Inventory alert','Delivery delay','Budget alert','Security alert']],
    ['h1','Colour semantics'],
    ['tbl',['Colour','Meaning'],[['Green','Completed / on-target'],['Blue','Informational'],['Orange','Warning · attention required'],['Red','Critical · immediate action'],['Grey','Inactive / disabled']],[20,80]],
    ['h1','Security'],
    ['ul',['Widget-level RBAC.','No direct database access from the client.','Every user action written to AuditLog.','Session timeout with configurable idle window.','MFA required for any Approve / Award action.','All traffic over TLS; WebSocket over WSS.']],
    ['h1','APIs required'],
    ['tbl',['Method + Path','Purpose'],[
      ['GET /api/purchasing/dashboard','Row-1 KPI card counts'],
      ['GET /api/purchasing/alerts','Row-3 alerts panel'],
      ['GET /api/purchasing/tasks','Row-2 AI Priority Queue'],
      ['GET /api/purchasing/timeline','Row-2 activity timeline'],
      ['GET /api/purchasing/kpi','Header + row-3 KPIs'],
      ['GET /api/suppliers/performance','Row-3 supplier performance'],
      ['GET /api/budget/status','Row-1 card 5 + row-3 budget'],
      ['GET /api/sos/inventory','Live inventory hooks for alerts'],
      ['GET /api/notifications','Header bell'],
      ['WS  /ws/purchasing','Live updates channel'],
    ],[42,58]],
    ['h1','Database tables used'],
    ['ul',['PurchaseRequests','PurchaseRequestItems','Suppliers','SupplierPerformance','RFQs','RFQResponses','PurchaseOrders','Receiving','Budget','Projects','Departments','Users','Notifications','AuditLog']],
    ['h1','KPIs displayed'],
    ['tbl',['KPI','Definition'],[
      ['Average Purchase Cycle','Days from PR submission to PO closed'],
      ['Average Supplier Response','Median time between RFQ sent and first quote received'],
      ['Savings','(Baseline − awarded price) × qty, monthly rolling'],
      ['Open RFQs','Count of RFQs whose status is Sent or Waiting'],
      ['Late Deliveries','PO lines past promised date and not fully received'],
      ['Budget Utilization','Committed + spent as % of allocated budget, monthly'],
      ['Supplier Score','Weighted mean of delivery, quality, service, price ratings'],
      ['Purchase Lead Time','Days from PO issued to first receipt'],
      ['Inventory Risk','SKUs projected to stock-out within lead time × unit cost'],
      ['Approval Time','Median hours from PR submitted to first approval action'],
    ],[30,70]],
    ['h1','Acceptance criteria'],
    ['ul',[
      'Dashboard loads in under 3 seconds on the reference workstation.',
      'All widgets respect role-based permissions; hidden data never reaches the client.',
      'Real-time updates occur without page refresh within 2 seconds of the source event.',
      'All counts reconcile exactly with the underlying transaction data.',
      'Every alert links directly to the transaction that raised it.',
      'Every user action is written to AuditLog (actor, timestamp, before/after, IP, device).',
      'Responsive from 1366×768 to 4K; no horizontal scroll at any size.',
      'MFA prompt appears before any Approve / Award action.',
    ]],
  ]
};

// Screen 002 — Purchase Request
const S002 = { n:'002', docId:'ACC-PUR-002', title:'Purchase Request',
  subtitle:'Entry point for every purchasing workflow',
  sections:[
    ['h1','Purpose'],
    ['p','Creates every purchase request in HydroNexis. Nothing can be purchased without an approved Purchase Request. Every PR receives a unique, immutable PR Number and is traceable through the workflow to a closed PO.'],
    ['h1','Access matrix'],
    ['tbl',['Role','Create','Edit','Approve','Cancel'],[
      ['Employee','Yes','Draft only','No','Draft only'],
      ['Department Manager','Yes','Yes','Level 1','Yes'],
      ['Purchasing Officer','Yes','Yes','No','Yes'],
      ['Purchasing Manager','Yes','Yes','Level 2','Yes'],
      ['Accounting Manager','Yes','Yes','Financial','Yes'],
      ['CEO','Yes','Yes','Final','Yes'],
    ],[26,14,18,20,22]],
    ['h1','PR Number'],
    ['p','Auto-generated on Save Draft.'],
    ['code','PR-YYYY-NNNNNN   (example: PR-2026-000458)'],
    ['p','Immutable once assigned. Sequence is monotonic per calendar year; resets on 1 January.'],
    ['h1','Header fields (read-only after creation)'],
    ['ul',['Purchase Request No.','Status','Created By','Created Date','Last Modified','Revision','Priority','Workflow Stage']],
    ['h1','Workflow'],
    ['tbl',['#','Stage','Exit condition'],[
      ['01','Draft','User clicks Submit and all Submit-Validation checks pass'],
      ['02','Submitted','AI Validation job completes'],
      ['03','AI Validation','No blocking issues, or user acknowledges warnings'],
      ['04','Department Approval','Level 1 approver decision recorded'],
      ['05','Purchasing Review','Purchasing Officer / Manager assigns handling'],
      ['06','Inventory Verification','SOS reconfirms need after pending transfers'],
      ['07','Supplier Sourcing','Suppliers selected or Supplier Discovery triggered'],
      ['08','RFQ','RFQ sent; awaiting responses'],
      ['09','Quotation Evaluation','At least one qualifying quote received and scored'],
      ['10','Approval','All required approval levels recorded'],
      ['11','Purchase Order','PO created and sent'],
      ['12','Receiving','Goods received against PO'],
      ['13','Completed','PO closed, three-way match complete'],
    ],[6,34,60]],
    ['h1','Main form — general information'],
    ['tbl',['Field','Type','Rule','Required'],[
      ['Request Title','Text','Max 150 chars','Yes'],
      ['Department','Dropdown','Sourced from Departments','Yes'],
      ['Project','Dropdown','Sourced from Projects','No'],
      ['Cost Center','Dropdown','Accounting integration','Yes'],
      ['Budget Code','Lookup','Accounting Budget','Yes'],
      ['Required Delivery Date','Date','≥ today; category-constrained','Yes'],
      ['Priority','Enum','Normal · High · Urgent · Emergency','Yes'],
      ['Justification','Text area','Min 30 · Max 3000 chars','Yes'],
    ],[24,14,46,16]],
    ['h1','Item grid'],
    ['p','A single PR may contain multiple items. Every row is independently validated.'],
    ['tbl',['Column','Rule'],[
      ['Line No.','Auto 1..N per PR'],
      ['Item Code','Free text OR lookup into SOS Items · triggers Intelligent Item Recognition'],
      ['Item Description','Populated from lookup, editable'],
      ['Category','Inherited from item; overridable'],
      ['Quantity','Positive number · decimals per unit definition'],
      ['Unit','From item master'],
      ['Estimated Unit Price','Populated from last purchase · editable'],
      ['Estimated Total','Computed: qty × unit price · read-only'],
      ['Currency','Defaults to company currency · overridable per line'],
      ['Preferred Brand','Optional; drives supplier suggestion ranking'],
      ['Alternative Brand Allowed','Boolean; if false, Nexi must not suggest substitutes'],
      ['Warehouse Destination','Which warehouse receives the goods'],
      ['Required Date','Per-line override of header Required Delivery Date'],
      ['Remarks','Free text'],
      ['Attachment','Per-line file upload'],
    ],[30,70]],
    ['h1','Intelligent item recognition'],
    ['p','When an Item Code is entered, Nexi queries every source and returns results inline within 500 ms:'],
    ['ul',['SOS Inventory (on-hand + reserved)','Previous purchases of this item','Supplier database','Warehouse availability (all sites)','Historical pricing (12 months, per supplier)','Open POs for the same item','Approved brands','Existing draft/submitted duplicate requests']],
    ['h1','Attachments'],
    ['tbl',['Rule','Value'],[
      ['Formats','PDF · DWG · DXF · Excel · Word · Images · Videos · ZIP'],
      ['Max size per file','500 MB'],
      ['Virus scan','Every upload scanned before persistence; failed scans quarantined and audit-logged'],
      ['Retention','Tied to the PR record; default 7 years'],
    ],[25,75]],
    ['h1','Budget validation'],
    ['p','Real-time. Every quantity or unit-price change re-runs the check. Checks: Budget Code availability · period remaining · Project budget · Department budget · monthly and annual allocation.'],
    ['tbl',['Result','Behaviour'],[
      ['OK','Green tick next to the amount'],
      ['Insufficient','Yellow warning — submission allowed with manager acknowledgement'],
      ['Exceeded','Red block — Submit disabled until fixed or override granted'],
    ],[30,70]],
    ['h1','Inventory validation'],
    ['p','Calls SOS Inventory on every recomputation: current stock · reserved · incoming · warehouse transfers in flight · alternative items.'],
    ['note','Rule','If inventory already exists that satisfies the request, Nexi recommends internal transfer and marks the line as blocked pending acknowledgement.'],
    ['h1','Duplicate detection'],
    ['p','Searches for open or submitted PRs matching all of: same item · same department · same project · same week · same preferred supplier · quantity band ±20%.'],
    ['h1','Buttons'],
    ['tbl',['Button','Effect'],[
      ['Save Draft','Persists as Draft; PR Number assigned on first save'],
      ['Submit','Advances to AI Validation stage'],
      ['Validate','Runs full validation without submitting'],
      ['Check Inventory','Forces fresh SOS query'],
      ['Find Supplier','Opens 6.1 AI Supplier Search seeded'],
      ['Estimate Cost','Refreshes unit-price estimates'],
      ['Cancel','Cancels PR (respects Access matrix)'],
      ['Print','Print-friendly view'],
      ['Export PDF','PDF with QR link back'],
      ['Clone Request','Duplicates into new Draft'],
    ],[22,78]],
    ['h1','APIs'],
    ['tbl',['Method + Path','Purpose'],[
      ['POST /api/purchasing/pr','Create new PR (Draft)'],
      ['PUT  /api/purchasing/pr/{id}','Update fields or line items'],
      ['GET  /api/purchasing/pr/{id}','Fetch a single PR with items + workflow state'],
      ['POST /api/purchasing/pr/{id}/submit','Advance to AI Validation'],
      ['POST /api/purchasing/pr/{id}/cancel','Cancel the PR'],
      ['POST /api/purchasing/pr/{id}/clone','Clone into a new Draft'],
      ['GET  /api/sos/items','Item lookup'],
      ['GET  /api/sos/stock','Current + reserved stock'],
      ['GET  /api/budget/check','Real-time budget validation'],
      ['GET  /api/projects','Project dropdown'],
      ['GET  /api/departments','Department dropdown'],
      ['GET  /api/suppliers/history','Supplier intelligence panel'],
      ['POST /api/attachments/upload','Multi-part upload'],
      ['POST /api/ai/pr/validate','Run AI validation'],
    ],[42,58]],
    ['h1','Database tables'],
    ['ul',['PurchaseRequest','PurchaseRequestItems','PurchaseRequestWorkflow','PurchaseRequestAttachments','Departments','Projects','Budget','Inventory','Suppliers','AuditLog','Notifications']],
    ['h1','Acceptance criteria'],
    ['ul',[
      'PR number is generated automatically and is immutable.',
      'A single PR supports N line items with independent, per-line validation.',
      'Budget checks and SOS inventory checks are real-time.',
      'Duplicate requests are surfaced before submission and require explicit acknowledgement.',
      'AI recommendations are non-blocking by default; policy flags can make specific ones blocking.',
      'All changes captured by the audit trail.',
      'Submission creates the workflow instance and notifies the next approver within 5 seconds.',
      'A submitted PR cannot be edited except through the versioned Revision mechanism.',
    ]],
  ]
};

// Screen 003 — AI Purchasing Analysis (SOS Inventory Intelligence)
const S003 = { n:'003', docId:'ACC-PUR-003', title:'AI Purchasing Analysis',
  subtitle:'SOS Inventory Intelligence — prevent unnecessary purchasing',
  sections:[
    ['h1','Purpose'],
    ['p','Immediately after a PR is submitted, Nexi performs a complete procurement analysis before any supplier is contacted. Prevent unnecessary purchasing. First determine whether the company already has the required item, an approved substitute, an incoming delivery, or another internal source.'],
    ['h1','Processing time'],
    ['p','Target: less than 5 seconds. Live progress indicator shows every step.'],
    ['ul',['Checking SOS Inventory…','Checking all warehouses…','Checking open Purchase Orders…','Checking incoming deliveries…','Checking approved alternatives…','Checking historical purchases…','Checking supplier contracts…','AI Analysis Complete.']],
    ['h1','Screen layout'],
    ['h2','Left panel — Purchase Request summary'],
    ['p','Read-only. Displays: PR Number · Requester · Department · Project · Required Date · Priority · Total Estimated Cost · Line Items · Approval Status.'],
    ['h2','Center panel — AI analysis'],
    ['p','Each requested item receives an analysis card. Example:'],
    ['tbl',['Field','Value'],[
      ['Item','2 HP Stainless Water Pump'],
      ['Inventory Status','Main 0 · GH1 1 · GH5 2 · GH10 0'],
      ['Total Available','3 units'],
      ['Required','2 units'],
      ['Recommendation','Internal Transfer'],
      ['Status','Purchase Not Required'],
      ['Savings','₱48,000'],
      ['Confidence','98%'],
    ],[30,70]],
    ['h2','Alternative item analysis'],
    ['p','If the requested item is unavailable, searches: approved equivalents · compatible brands · previous substitutions · engineering approvals · manufacturer compatibility.'],
    ['tbl',['Requested','Suggested','Compatibility'],[['Pump A','Pump B','99%']],[35,35,30]],
    ['h2','Incoming deliveries'],
    ['p','Checks approved POs. Example: Supplier ABC Industrial · Delivery tomorrow · Qty 10 · Reserved 2 · Available 8 · Recommendation: Delay Purchase.'],
    ['h2','Existing contracts'],
    ['p','Searches: Framework agreements · Annual contracts · Corporate agreements · Negotiated pricing.'],
    ['tbl',['Field','Displayed'],[
      ['Supplier','Name'],['Contract Number','Ref'],['Expiration','Date'],['Price','Locked rate'],['Remaining Allocation','Units / value']
    ],[30,70]],
    ['h2','Warehouse transfer analysis'],
    ['p','Instead of buying: can another warehouse supply it? Example: Move GH8 → Main · Transport ₱450 · Purchase cost ₱24,000 · Recommendation: Transfer.'],
    ['h2','Historical price analysis'],
    ['ul',['Last Purchase Price','Average Price','Highest Price','Lowest Price','Current Estimate','Inflation','Price Trend','Price Volatility','Price Prediction']],
    ['p','Example: Average ₱2,450 · Expected market ₱2,320 · Recommendation: Wait 7 days · Estimated savings ₱18,500.'],
    ['h2','Consumption analysis'],
    ['ul',['Average Monthly Usage','Maximum Usage','Minimum Usage','Current Consumption','Inventory Turnover','Forecast']],
    ['p','Example: Current inventory covers 4 months · Recommendation: No purchase required.'],
    ['h2','Duplicate purchase detection'],
    ['p','Searches: all PRs · open RFQs · open POs · recent deliveries. Shows any duplicate, e.g. PR-2026-00481 same department, same item, same quantity. Decision: Merge Requests.'],
    ['h2','Supplier availability'],
    ['p','Without sending an RFQ yet. Displays: approved suppliers · last supplier · rating · avg delivery · lead time · quality · response time · warranty claims.'],
    ['h1','AI Decision Panel'],
    ['p','Displays one final recommendation. Possible results:'],
    ['ul',['Purchase Immediately','Transfer Inventory','Wait for Delivery','Use Existing Contract','Delay Purchase','Use Alternative Item','Combine Purchase Requests','Reject Request','Escalate to Engineering','Escalate to Finance']],
    ['p','Each recommendation includes: Confidence % · Estimated Savings · Estimated Delay · Risk Level · Reasoning.'],
    ['h1','User actions'],
    ['ul',['Approve AI Recommendation','Override Recommendation','Request Manual Review','Proceed to Supplier Search','Back to Purchase Request','Export Analysis']],
    ['h1','Override rules'],
    ['p','If a user overrides Nexi, they must enter: Reason · Business Justification · Approval (if required). Override is permanently recorded.'],
    ['h1','Integrations (read-only)'],
    ['ul',['SOS Inventory','Warehouse','Projects','Accounting','Supplier Database','Contracts','Purchase Orders','Receiving']],
    ['h1','Required APIs'],
    ['tbl',['Method + Path','Purpose'],[
      ['GET  /api/sos/stock-all','All-warehouse stock snapshot'],
      ['GET  /api/sos/transfers','In-flight transfers'],
      ['GET  /api/contracts','Active supplier contracts'],
      ['GET  /api/purchase-orders/open','Open POs relevant to the requested items'],
      ['GET  /api/inventory/history','Consumption + turnover history'],
      ['GET  /api/forecast','Consumption forecast'],
      ['GET  /api/price-history','Historical + market price series'],
      ['GET  /api/suppliers','Supplier availability lookup'],
      ['POST /api/ai/purchase-analysis','Runs the complete analysis, returns the AI decision packet'],
    ],[38,62]],
    ['h1','Database tables'],
    ['ul',['Inventory','WarehouseInventory','InventoryTransfers','PurchaseOrders','PurchaseOrderItems','SupplierContracts','HistoricalPrices','ForecastConsumption','PurchaseRequest','SupplierPerformance','AuditLog']],
    ['h1','KPIs'],
    ['ul',['Purchases Avoided','Internal Transfers Recommended','Savings from Inventory Reuse','Duplicate Requests Prevented','Contract Utilization','Average Inventory Coverage','AI Recommendation Accuracy']],
    ['h1','Acceptance criteria'],
    ['ul',[
      'Analysis completes in under 5 seconds under normal load.',
      'Every line item is evaluated independently.',
      'Recommendations include confidence, estimated savings, and rationale.',
      'Overrides require justification and are fully audited.',
      'Users can proceed to Supplier Search only after the analysis is complete or an override is approved.',
      'All inventory, contract, and PO data are read live from integrated systems.',
    ]],
    ['note','Architecture recommendation','This screen should be the MANDATORY AI GATE. No RFQ may be issued until this screen completes successfully. Ensures the company does not contact suppliers when stock, transfers, contracts, or incoming deliveries already satisfy the need.'],
  ]
};

// Screen 004 — Supplier Discovery & Intelligence
const S004 = { n:'004', docId:'ACC-PUR-004', title:'Supplier Discovery & Intelligence',
  subtitle:'Discover, evaluate, rank and recommend suppliers before any RFQ is sent',
  sections:[
    ['h1','Purpose'],
    ['p','Automatically identify the best suppliers for the requested item. Not simply "find suppliers." Nexi intelligently discovers, evaluates, ranks and recommends suppliers before any RFQ is sent.'],
    ['h1','Trigger'],
    ['p','Automatically opens after AI Purchasing Analysis returns PURCHASE REQUIRED.'],
    ['h1','Objectives'],
    ['ul',['Local Suppliers','International Suppliers','Manufacturers','Distributors','Existing Approved Suppliers','New Potential Suppliers']],
    ['h1','Search sources'],
    ['h2','Internal'],
    ['ul',['HydroNexis Supplier Database','Previous Purchases','Approved Vendor List','Supplier Performance History','Contracts','SOS Inventory Supplier Records']],
    ['h2','External (configurable per company policy)'],
    ['ul',['Manufacturer websites','Official distributor databases','Supplier directories','Trade association databases','Approved procurement portals']],
    ['h1','Search criteria'],
    ['ul',['Item Description','Item Code','Manufacturer','Brand','Category','Country','Lead Time','MOQ','Budget','Incoterms','Required Certifications','Warranty','Currency','Language']],
    ['h1','Search filters'],
    ['tbl',['Filter','Options'],[
      ['Location','Philippines · Asia · Worldwide'],
      ['Supplier type','Manufacturer · Distributor · Dealer · Importer · OEM'],
      ['Business type','Corporation · SME · Government · Preferred Vendor'],
      ['Risk','Low · Medium · High'],
      ['Certification','ISO · FDA · GAP · Organic · CE · UL · RoHS · Custom'],
    ],[25,75]],
    ['h1','Results — Supplier Intelligence Card'],
    ['p','Each supplier appears as a card. Displays:'],
    ['ul',['Company Name','Logo','Country','Years in Business','Products Offered','Supplier Type','Rating','Risk Level','Preferred Status','Last Purchase','Lead Time','Minimum Order','Response Time','Payment Terms','Warranty','Delivery Rating','Quality Rating','Overall Score']],
    ['h1','Supplier 360°'],
    ['p','Selecting a supplier opens the Supplier Profile. Displays:'],
    ['ul',['Company Information','Business Registration','Tax Registration','Address','Website','Primary / Secondary / Emergency Contact','Email · SMS · WhatsApp (optional)','Bank Information (restricted)','Insurance','Certifications','Factory Locations','Warehouse Locations','Service Centers']],
    ['h2','Historical purchasing'],
    ['ul',['Total Purchases','Last Purchase Date','Average Purchase Value','Average Delivery Time','Late Deliveries','Rejected Deliveries','Warranty Claims','Price Stability','Relationship Duration']],
    ['h2','Supplier performance KPIs'],
    ['ul',['On-Time Delivery %','Quality %','Average Response Time','Quotation Accuracy','Invoice Accuracy','Communication Score','Complaint Count','Corrective Actions','Overall AI Rating']],
    ['h1','AI Supplier Score — default weighting'],
    ['tbl',['Criterion','Weight'],[
      ['Commercial Competitiveness','20%'],
      ['Quality History','20%'],
      ['Delivery Performance','15%'],
      ['Financial Stability','10%'],
      ['Response Speed','10%'],
      ['Pricing Trend','10%'],
      ['Risk Assessment','10%'],
      ['Sustainability','5%'],
    ],[50,50]],
    ['p','Administrators can adjust the weighting.'],
    ['h1','AI recommendations'],
    ['ul',['Preferred Supplier','Lowest Cost','Fastest Delivery','Highest Quality','Lowest Risk','Best Overall Value','Existing Contract Available','Alternative Supplier Recommended']],
    ['h1','Duplicate detection'],
    ['p','Warn if: supplier already responding to another RFQ · suspended · blacklisted · under investigation · contract expired.'],
    ['h1','Risk engine'],
    ['ul',['Financial Risk','Country Risk','Currency Risk','Supply Chain Risk','Delivery Risk','Quality Risk','Compliance Risk','Cybersecurity Risk (for digital vendors)']],
    ['p','Each risk is scored and color-coded.'],
    ['h1','Communication readiness'],
    ['ul',['Verified Email','Verified Phone','Preferred Contact Method','Business Hours','Time Zone','Primary Language','Average Reply Time','Last Contact Date']],
    ['h1','Multi-supplier selection'],
    ['p','User can select multiple suppliers for the RFQ. Displays: estimated competition level · expected response probability · coverage of all requested items · recommended number of suppliers.'],
    ['h1','Actions'],
    ['ul',['View Profile','Compare Suppliers','Select for RFQ','Add to Preferred Vendors','Flag for Review','Suspend Supplier','Create New Supplier','Export Supplier Profile']],
    ['h1','Security'],
    ['p','Only Purchasing Managers and Administrators can: approve new suppliers · suspend suppliers · modify supplier ratings · view bank information. Everyone else has role-based restrictions.'],
    ['h1','APIs'],
    ['tbl',['Method + Path','Purpose'],[
      ['GET  /api/suppliers/search','Cross-source supplier search'],
      ['GET  /api/suppliers/profile/{id}','Supplier 360 profile'],
      ['GET  /api/suppliers/history/{id}','Historical purchasing'],
      ['GET  /api/suppliers/performance/{id}','KPI panel'],
      ['GET  /api/contracts/{supplierId}','Contract lookup'],
      ['POST /api/suppliers/qualification','Kick off qualification'],
      ['POST /api/suppliers/select','Select for RFQ'],
    ],[42,58]],
    ['h1','Database tables'],
    ['ul',['Suppliers','SupplierContacts','SupplierPerformance','SupplierCertificates','SupplierContracts','SupplierRisk','SupplierRatings','SupplierCommunications','SupplierCategories','SupplierBankAccounts (encrypted)','AuditLog']],
    ['h1','Acceptance criteria'],
    ['ul',[
      'Search returns results from all enabled data sources.',
      'Every supplier receives an AI score and visible explanation.',
      'Users can compare multiple suppliers side by side.',
      'Only authorized users can modify supplier records or view sensitive information.',
      'Selected suppliers flow directly into the RFQ process without re-entry.',
      'Every supplier action is written to the audit log.',
    ]],
    ['note','Architecture recommendation','Build a SUPPLIER KNOWLEDGE GRAPH behind this screen. Instead of storing suppliers as isolated records, Nexi maintains relationships between: suppliers · products · categories · purchase history · projects · warehouses · contracts · performance · quality issues · employees who worked with them. Enables questions like "Who is the best supplier we\'ve ever used for stainless pumps?" and "Which suppliers have the lowest total cost of ownership over 5 years?"'],
  ]
};

// Screen 005 — RFQ Management Center
const S005 = { n:'005', docId:'ACC-PUR-005', title:'RFQ Management Center',
  subtitle:'Prepare, distribute, track, follow up, and evaluate supplier responses',
  sections:[
    ['h1','Purpose'],
    ['p','Manages the complete quotation process. Instead of manually emailing suppliers, Nexi prepares, distributes, tracks, follows up, and evaluates responses. One RFQ may contain one or many PR items. One RFQ may be sent to one or many suppliers.'],
    ['h1','Entry conditions'],
    ['ul',['Purchase Request Approved','AI Purchasing Analysis Complete','Supplier Selection Complete']],
    ['h1','Header'],
    ['fl',['RFQ Number: RFQ-YYYY-NNNNNN','Status: Draft · Sent · Partially Responded · Completed · Cancelled · Expired','Buyer','Creation Date','Closing Date','Currency','Revision Number']],
    ['h1','Left panel — RFQ summary'],
    ['ul',['Purchase Request Number','Department','Project','Budget','Total Estimated Value','Number of Items','Number of Suppliers','Closing Date','Priority']],
    ['h1','Timeline'],
    ['flow',['Draft','Approved','Sent','Supplier Opened','Supplier Replied','Clarification','Quotation Complete','Comparison Ready']],
    ['h1','Center panel — items included'],
    ['tbl',['Column','Notes'],[
      ['Line','Auto per RFQ'],['Item','Ref to PR item'],['Description','From item master'],
      ['Specification','Preview inline'],['Quantity','Number'],['Unit','From item master'],
      ['Required Delivery Date','Per line, may override header'],['Attachment','Drawings open inline'],['Comments','Free text'],
    ],[22,78]],
    ['h1','Supplier list'],
    ['tbl',['Column','Notes'],[
      ['Supplier Name',''],['Country',''],['Contact Person',''],
      ['Email','Verified'],['SMS','Verified'],['Last Response Time',''],
      ['Supplier Rating',''],['Status','see below'],['Selected','Checkbox'],
    ],[26,74]],
    ['h2','Supplier status values'],
    ['ul',['Draft','Queued','Sent','Delivered','Opened','Downloaded Attachment','Replied','Partial Reply','Completed','No Response','Declined']],
    ['h1','Right panel — Nexi RFQ Assistant'],
    ['ul',['Increase Supplier Count','Include Manufacturer','Split RFQ','Combine RFQ','Recommended Closing Date','Suggested Delivery Terms','Suggested Payment Terms','Risk Warnings']],
    ['h1','RFQ generation'],
    ['p','Nexi automatically creates a Professional RFQ PDF containing: technical specifications · commercial requirements · delivery requirements · warranty requirements · company terms · confidentiality statement · submission instructions · attachments. No manual composition required.'],
    ['h1','Communication methods'],
    ['ul',['Email','SMS','Supplier Portal','API (future)','EDI (future)']],
    ['p','Buyer chooses one or more.'],
    ['h1','Email tracking (per supplier)'],
    ['ul',['Sent','Delivered','Opened','Clicked','Downloaded Attachment','Replied','Bounce','Failure','Spam','Timestamp']],
    ['h1','SMS tracking (per supplier)'],
    ['ul',['Sent','Delivered','Read','Reply Received','Failed','Retry']],
    ['h1','Supplier Portal (recommended)'],
    ['p','Each supplier receives a secure one-time-token link (no login). Supplier can: Download RFQ · Ask Questions · Upload Quotation · Upload Certificates · Update Delivery · Accept NDA · Submit Response · View Deadline. Link expires automatically after the RFQ closes.'],
    ['h1','Clarification management'],
    ['p','Every supplier question becomes a ticket visible to Purchasing, Engineering, Requester. Answers can be private (only to that supplier) or shared with all participating suppliers to ensure fairness.'],
    ['h1','AI monitoring'],
    ['ul',['Which suppliers have not opened the RFQ','Who opened but did not respond','Expected response probability','Recommended reminders','Suppliers likely to decline','Supplier workload']],
    ['h1','Automatic follow-up (configurable)'],
    ['tbl',['Day','Action'],[
      ['Day 2','Reminder Email'],['Day 4','Reminder SMS'],['Day 6','Buyer Notification'],['Day 7','AI Recommendation: invite additional supplier'],
    ],[20,80]],
    ['h1','Attachment manager'],
    ['ul',['Supports PDF · DWG · DXF · Word · Excel · ZIP · Photos · Videos','Checksum · Virus scan · Version number · Digital signature (optional) per file']],
    ['h1','RFQ version control'],
    ['p','Any modification creates a Revision (number, modified by, reason, affected suppliers). Suppliers automatically receive the updated version. Old versions remain available for audit.'],
    ['h1','Buyer actions'],
    ['ul',['Create RFQ','Preview RFQ','Edit','Duplicate','Save Draft','Send','Pause','Cancel','Extend Closing Date','Add Supplier','Remove Supplier','Generate PDF','Export Excel','Archive']],
    ['h1','AI risk engine — alerts'],
    ['ul',['Too Few Suppliers','Supplier Monopoly','Budget Too Low','Specification Too Restrictive','High Risk Supplier','Unusually Short Deadline','Potential Collusion Indicator','Contract Conflict']],
    ['h1','Security'],
    ['p','Suppliers cannot see: other suppliers · other quotations · internal notes · budgets · AI recommendations · internal comments. Every supplier has isolated access.'],
    ['h1','APIs'],
    ['tbl',['Method + Path','Purpose'],[
      ['POST /api/rfq/create','Create RFQ'],
      ['PUT  /api/rfq/update','Update RFQ (creates revision)'],
      ['POST /api/rfq/send','Dispatch to selected suppliers'],
      ['GET  /api/rfq/status','Aggregate + per-supplier status'],
      ['GET  /api/rfq/suppliers','Suppliers on this RFQ'],
      ['POST /api/email/send','Email dispatch'],
      ['POST /api/sms/send','SMS dispatch'],
      ['POST /api/rfq/portal','Provision one-time-token portal link'],
      ['POST /api/rfq/reminder','Manual reminder'],
    ],[38,62]],
    ['h1','Database tables'],
    ['ul',['RFQ','RFQItems','RFQSuppliers','RFQAttachments','RFQVersions','RFQCommunications','RFQQuestions','RFQResponses','EmailQueue','SMSQueue','AuditLog']],
    ['h1','KPIs'],
    ['ul',['Average RFQ Cycle Time','Supplier Response Rate','Average Response Time','No Response Rate','RFQ Completion Rate','Average Suppliers per RFQ','Reminder Effectiveness']],
    ['h1','Acceptance criteria'],
    ['ul',[
      'An RFQ cannot be sent without at least one approved supplier.',
      'Every supplier receives only the information intended for them.',
      'All communications are tracked with timestamps.',
      'Revisions are version-controlled and auditable.',
      'Automated reminders follow configurable schedules.',
      'Every supplier response is linked back to the originating RFQ and PR.',
      'The buyer has a complete real-time view of supplier engagement from a single screen.',
    ]],
    ['note','Enhancement — Digital Procurement Workspace','For each RFQ, create a secure workspace centralising: RFQ documents · technical clarifications · email history · SMS history · uploaded quotations · certificates · delivery commitments · negotiation history · AI summaries · approval history. The buyer never searches through Outlook or WhatsApp because every procurement conversation lives with the RFQ itself.'],
  ]
};

// Screen 006 — AI Quotation Analysis & Comparison
const S006 = { n:'006', docId:'ACC-PUR-006', title:'AI Quotation Analysis & Comparison',
  subtitle:'Automatic extraction, comparison, TCO calculation, best-supplier recommendation',
  sections:[
    ['h1','Purpose'],
    ['p','Automatically receive supplier quotations, extract all commercial and technical information, compare every quotation, detect inconsistencies, calculate the true procurement cost, and recommend the best supplier. The Purchasing Officer should never manually build Excel comparison sheets again.'],
    ['h1','Entry conditions'],
    ['ul',['RFQ closed or minimum quotation requirement reached','At least one supplier quotation received','RFQ status = "Ready for Evaluation"']],
    ['h1','Layout'],
    ['p','Three-panel interface.'],
    ['h2','Left panel — RFQ information'],
    ['ul',['RFQ Number','Purchase Request','Project','Department','Buyer','Closing Date','Number of Suppliers Invited','Number of Quotations Received','Currency','Total Estimated Budget']],
    ['h2','Center panel — supplier comparison matrix'],
    ['p','One row per supplier. Columns:'],
    ['ul',['Supplier','Overall AI Score','Commercial Score','Technical Score','Quality Score','Delivery Score','Risk Score','Warranty Score','Compliance Score','Total Cost','Recommendation','Status']],
    ['p','Selecting a supplier expands complete quotation details.'],
    ['h2','Right panel — Nexi recommendation'],
    ['ul',['Recommended Supplier','Second Choice','Savings','Risks','Concerns','Negotiation Opportunities','Confidence','Overall Recommendation']],
    ['h1','AI quotation extraction'],
    ['p','When quotation files arrive, Nexi automatically extracts:'],
    ['ul',['Supplier Name','Quotation Number','Date','Currency','Item List','Unit Prices','Discounts','Taxes','Freight','Insurance','Lead Time','Delivery Terms','Payment Terms','Warranty','Validity','Incoterms','Special Conditions','Minimum Order','Certificates']],
    ['p','No manual encoding.'],
    ['h1','File types & OCR'],
    ['ul',['Formats: PDF · Excel · Word · Images · Scanned Documents · ZIP · Email Attachments','If scanned: run OCR to extract tables, prices, text, signatures, dates, item codes automatically']],
    ['h1','Technical comparison'],
    ['tbl',['Field','Displayed'],[
      ['Requested Specification','from PR / RFQ'],['Supplier Specification','from quotation'],
      ['Compliance %','computed'],['Missing Features',''],['Additional Features',''],
      ['Engineering Comments','free text'],['AI Technical Rating','0-100'],
    ],[35,65]],
    ['h1','Commercial comparison'],
    ['ul',['Unit Price','Discount','Extended Price','Taxes','Shipping','Insurance','Installation','Training','Support','Maintenance','Spare Parts','Grand Total']],
    ['h1','Landed cost calculation'],
    ['p','Real purchasing cost. Formula:'],
    ['code','Total Ownership Cost = Purchase + Shipping + Insurance + Import Duties + Brokerage + Transport + Installation + Commissioning + Training + Expected Maintenance'],
    ['p','This — not just purchase price — drives supplier ranking.'],
    ['h1','Delivery comparison'],
    ['p','Example: Supplier A 14 days · Supplier B 21 days · Supplier C 45 days. Also evaluates historical delivery accuracy, average delay, delivery reliability.'],
    ['h1','Warranty analysis'],
    ['ul',['Warranty Duration','Coverage','Replacement Time','On-site Service','Parts Availability','Warranty History']],
    ['h1','Quality history'],
    ['ul',['Accepted %','Rejected %','Returned %','Corrective Actions','Complaints','Quality Trend']],
    ['h1','Financial analysis'],
    ['ul',['Price Stability','Currency Exposure','Payment Terms','Credit Limit','Financial Risk','Outstanding Issues']],
    ['h1','AI risk detection'],
    ['ul',['Unusually Low Price','Missing Specification','Hidden Costs','Incomplete Quote','Expired Quotation','Suspicious Discount','Supplier Dependency','Collusion Indicators']],
    ['h1','Comparison modes'],
    ['ul',['Lowest Price','Fastest Delivery','Best Quality','Lowest Risk','Best Total Value','Custom Weighted Score']],
    ['h1','AI Recommendation Engine'],
    ['p','Produces: Executive Summary · Recommended Supplier · Second Choice · Why · Savings · Risks · Negotiation Suggestions · Expected ROI · Confidence Score. No black-box decisions — every recommendation includes a visible explanation.'],
    ['h1','Buyer actions'],
    ['ul',['Open Quotation','Compare','Request Clarification','Start Negotiation','Reject Supplier','Shortlist','Recommend Award','Export Comparison (PDF / Excel)']],
    ['h1','Visualisations'],
    ['ul',['Price Distribution','Supplier Score Radar','Lead Time Comparison','Quality Trend','Cost Breakdown','Delivery Performance','Historical Price Trend']],
    ['h1','Security'],
    ['p','Quotations cannot be modified. Original supplier documents remain immutable. All extracted values link back to the original document. Only Purchasing Managers and authorized Accounting users can finalize supplier recommendations.'],
    ['h1','APIs'],
    ['tbl',['Method + Path','Purpose'],[
      ['POST /api/quotation/upload','Upload supplier quotation'],
      ['POST /api/quotation/extract','Run OCR + extraction'],
      ['GET  /api/quotation/compare','Compute comparison matrix'],
      ['GET  /api/quotation/technical','Technical comparison payload'],
      ['GET  /api/quotation/commercial','Commercial comparison payload'],
      ['GET  /api/quotation/risk','Risk detection results'],
      ['POST /api/quotation/recommendation','Produce recommendation packet'],
    ],[42,58]],
    ['h1','Database tables'],
    ['ul',['Quotation','QuotationItems','QuotationExtraction','QuotationComparison','SupplierScores','CommercialEvaluation','TechnicalEvaluation','RiskAssessment','Recommendation','AuditLog']],
    ['h1','KPIs'],
    ['ul',['Average Savings Achieved','Average Evaluation Time','AI Extraction Accuracy','Negotiation Opportunity Value','Average Supplier Score','Evaluation Completion Time','Total Cost of Ownership Savings']],
    ['h1','Acceptance criteria'],
    ['ul',[
      'Quotations are parsed automatically from supported file types.',
      'Every extracted value is traceable to the source document.',
      'Technical and commercial evaluations are displayed side by side.',
      'Total Cost of Ownership is calculated consistently for every supplier.',
      'AI recommendations include explanations, confidence scores, and identified risks.',
      'All recommendation changes and user overrides are fully audited.',
    ]],
    ['note','Enhancement — Explainable AI','Every recommendation must answer "Why?" with evidence. Example — Recommended Supplier: ABC Industrial. Reasoning: Lowest TCO ₱2,845,000 · 98.4% historical on-time delivery · 0 warranty claims 24 months · 99.2% specification compliance · existing framework agreement reduces cycle 6 days · savings vs next-ranked ₱187,450. Buyer can expand each point to see the underlying data and calculations.'],
  ]
};

// Screen 007 — AI Negotiation Center
const S007 = { n:'007', docId:'ACC-PUR-007', title:'AI Negotiation Center',
  subtitle:'Nexi as the buyer\'s intelligent negotiation assistant',
  sections:[
    ['h1','Purpose'],
    ['p','After quotations are evaluated, Purchasing begins negotiations with shortlisted suppliers. Nexi becomes the buyer\'s intelligent negotiation assistant — recommending negotiation strategies, identifying opportunities, tracking concessions, and maintaining a complete negotiation history.'],
    ['h1','Objectives'],
    ['ul',['Reduce purchase cost','Improve payment terms','Improve delivery time','Increase warranty','Reduce risk','Maintain supplier relationship','Record every negotiation']],
    ['h1','Entry conditions'],
    ['ul',['RFQ Evaluation Completed','Supplier Shortlist Approved','Negotiation Required']],
    ['h1','Layout — three panels'],
    ['h2','Left panel — supplier list'],
    ['ul',['Supplier','Current Rank','AI Score','Current Offer','Negotiation Status','Last Contact','Response SLA','Risk Indicator']],
    ['p','Color codes: 🟢 Active · 🟡 Waiting Response · 🔴 Overdue · ⚫ Closed'],
    ['h2','Center panel — negotiation workspace'],
    ['p','Every communication is displayed chronologically. Channels: Email · SMS · Supplier Portal · Internal Notes. Each message contains: Date & Time · Sender · Recipient · Subject · Attachments · AI Summary · Read Status. Nothing is deleted.'],
    ['h2','Right panel — Nexi negotiation assistant'],
    ['tbl',['Field','Example'],[
      ['Current Supplier Price','₱1,250'],['Historical Average','₱1,180'],
      ['Best Competitor','₱1,165'],['Recommended Counter Offer','₱1,170'],
      ['Confidence','93%'],['Expected Acceptance','78%'],['Estimated Savings','₱184,000'],
    ],[35,65]],
    ['h1','Negotiation categories'],
    ['ul',['Price','Lead Time','Warranty','Payment Terms','Delivery Schedule','Packaging','Training','Installation','Technical Support','Spare Parts','After-Sales Service','Penalty Clauses','Service-Level Agreement','Incoterms']],
    ['h1','AI negotiation analysis'],
    ['ul',['Price Reduction Potential','Delivery Improvements','Warranty Gaps','Commercial Risks','Missing Conditions','Hidden Costs','Supplier Weaknesses','Competitive Advantages','Historical Negotiation Success']],
    ['h1','Concession tracker'],
    ['tbl',['Category','Buyer','Supplier'],[
      ['Price','Requested 8%','Approved 5%'],
      ['Delivery','30 Days','21 Days'],
      ['Warranty','12 Months','24 Months'],
      ['Payment','30 Days','45 Days'],
    ],[30,35,35]],
    ['h1','Offer comparison'],
    ['flow',['Revision 1','Revision 2','Revision 3','Final Offer']],
    ['p','Differences are highlighted automatically between revisions.'],
    ['h1','AI opportunity detection'],
    ['ul',['Supplier reduced price for another project previously','Delivery can be improved based on historical performance','Payment terms better than requested','Free installation available','Warranty extension likely','Annual contract discount possible']],
    ['h1','Negotiation playbook (configurable)'],
    ['tbl',['Trigger','Rule'],[
      ['Purchase Value > ₱5,000,000','Always negotiate price'],
      ['Delivery > 30 Days','Negotiate delivery'],
      ['Warranty < Company Standard','Negotiate warranty'],
    ],[45,55]],
    ['h1','Communication composer'],
    ['ul',['Email · SMS · Supplier Portal','Templates · AI Draft · Manual Edit','Attachment Manager','Preview Before Sending']],
    ['h1','AI draft generator'],
    ['p','Example: "Based on your quotation, we appreciate your proposal. To move forward, we request consideration of the following revisions…" The buyer can edit before sending. Nexi never sends communications automatically unless company policy explicitly enables it.'],
    ['h1','Internal collaboration'],
    ['p','Purchasing can request input from Engineering · Production · Maintenance · Accounting · Management. Internal discussions remain invisible to suppliers.'],
    ['h1','Negotiation dashboard'],
    ['ul',['Average Savings','Negotiation Duration','Suppliers Active','Pending Responses','Average Response Time','Negotiation Success Rate']],
    ['h1','Security'],
    ['p','Only assigned buyers can negotiate. Managers can monitor. Executives have read-only access. All negotiations are encrypted. Digital signatures optional.'],
    ['h1','APIs'],
    ['tbl',['Method + Path','Purpose'],[
      ['GET  /api/negotiation/{rfqId}','Get negotiation state'],
      ['POST /api/negotiation/message','Send message'],
      ['POST /api/negotiation/email','Email dispatch'],
      ['POST /api/negotiation/sms','SMS dispatch'],
      ['POST /api/negotiation/revision','Record offer revision'],
      ['GET  /api/negotiation/history','Full history'],
      ['POST /api/ai/negotiation-advice','Nexi advice packet'],
    ],[42,58]],
    ['h1','Database tables'],
    ['ul',['Negotiation','NegotiationMessages','NegotiationOffers','NegotiationRevisions','NegotiationAttachments','NegotiationConcessions','InternalComments','AuditLog']],
    ['h1','KPIs'],
    ['ul',['Average Cost Reduction','Average Negotiation Time','Negotiation Success Rate','Average Warranty Improvement','Average Delivery Improvement','Supplier Acceptance Rate','Savings Generated']],
    ['h1','Acceptance criteria'],
    ['ul',[
      'Every negotiation message is permanently linked to the RFQ and supplier.',
      'All supplier offer revisions are version-controlled.',
      'AI suggestions are advisory and require user confirmation before communication.',
      'Concessions are tracked by category and visible in the negotiation history.',
      'Internal discussions remain isolated from supplier communications.',
      'Complete audit history is retained for every negotiation action.',
    ]],
    ['note','Enhancement — Negotiation Intelligence Memory','Nexi should learn from every completed negotiation. For each supplier she builds a negotiation profile: typical discount range accepted · avg number of negotiation rounds · preferred channel · avg response time · areas of flexibility · seasonal pricing trends · common reasons for rejecting requests. New negotiations start with strategies tailored to that specific supplier.'],
  ]
};

// Screen 008 — AI Award Recommendation
const S008 = { n:'008', docId:'ACC-PUR-008', title:'AI Award Recommendation',
  subtitle:'Nexi recommends. An authorized approver decides.',
  sections:[
    ['h1','Purpose'],
    ['p','After negotiations are complete, Nexi evaluates all final offers and recommends the supplier(s) that provide the best overall value.'],
    ['note','Important rule','Nexi NEVER awards a contract. Nexi only recommends. An authorized company approver makes the final decision.'],
    ['h1','Entry conditions'],
    ['ul',['Negotiation completed','Final quotations received','Technical evaluation completed','Commercial evaluation completed','Budget approved']],
    ['h1','Layout — three columns'],
    ['h2','Left panel — procurement summary'],
    ['ul',['Purchase Request','RFQ','Buyer','Department','Project','Budget','Currency','Total Purchase Value','Number of Suppliers Evaluated','Negotiation Completed']],
    ['h2','Supplier ranking'],
    ['tbl',['Rank','Supplier','Score'],[
      ['1','ABC Industrial','96.8'],
      ['2','XYZ Engineering','94.1'],
      ['3','Prime Industrial','90.5'],
    ],[15,55,30]],
    ['h2','Center panel — award comparison matrix'],
    ['p','Each criterion displays Score · Weight · Weighted Score · Reason. Criteria:'],
    ['ul',['Commercial','Technical','Delivery','Warranty','Risk','Financial','Support','Past Performance','Sustainability','Compliance','Innovation','Contract Terms']],
    ['h2','Total Cost of Ownership'],
    ['ul',['Purchase Price','Freight','Insurance','Taxes','Import Duties','Installation','Commissioning','Training','Maintenance','Expected Spare Parts','Five-Year Ownership Cost']],
    ['p','Not just purchase price.'],
    ['h2','Value analysis'],
    ['tbl',['','Supplier A','Supplier B','Recommendation'],[
      ['Purchase Price','₱4,800,000','₱4,950,000','Supplier B'],
      ['Five-Year Cost','₱5,300,000','₱5,020,000','Lower TCO'],
    ],[25,25,25,25]],
    ['h2','Right panel — Nexi recommendation'],
    ['ul',['Recommended Supplier','Confidence','Overall Score','Business Risk','Savings','Reasoning','Expected Delivery','Expected ROI','Decision Summary']],
    ['h1','Explainable AI'],
    ['p','Every recommendation includes: Why this supplier · Why not the others · Risks · Trade-offs · Financial impact · Operational impact · Confidence level. Nothing is hidden.'],
    ['h1','Recommendation modes'],
    ['ul',['Lowest Price','Best Value','Fastest Delivery','Lowest Risk','Highest Quality','Lowest Total Cost of Ownership','Custom Company Policy']],
    ['p','Purchasing Management configures the default.'],
    ['h1','Multi-award'],
    ['p','Supports Single Supplier · Split Award · Regional Award · Category Award · Percentage Award (e.g. Supplier A 70% · Supplier B 30%).'],
    ['h1','Scenario simulator'],
    ['p','Buyer can test: "What if Supplier A reduces price by 5%?" · "What if Supplier B delivers in 10 days?" · "What if warranty becomes 5 years?" Every scenario recalculates the ranking instantly. Simulations do not modify live data.'],
    ['h1','Conflict detection'],
    ['ul',['Supplier is suspended','Supplier exceeds concentration policy','Budget exceeded','Contract conflict','Missing approvals','Compliance expired','Insurance expired','Required certifications missing']],
    ['h1','Executive summary (one page)'],
    ['ul',['Purchase Objective','Recommended Supplier','Alternative Supplier','Financial Summary','Key Risks','Key Benefits','Savings','Approval Recommendation','Export to PDF']],
    ['h1','Decision options'],
    ['ul',['Approve Recommendation','Select Different Supplier','Split Award','Return for Negotiation','Reject All Quotations','Cancel Procurement','Escalate to Executive Review']],
    ['h1','Override rules'],
    ['p','If the approver selects a supplier other than Nexi\'s recommendation, mandatory fields: Reason · Business justification · Supporting documents (optional) · Second approval (if required). Override is permanently recorded.'],
    ['h1','Approval preview'],
    ['flow',['Purchasing Manager','Accounting Manager','Finance Director (by value)','CEO (by approval limit)','Board (optional, configurable)']],
    ['h1','Security'],
    ['p','Only authorized approvers can finalize recommendations. Nexi cannot approve purchases. Recommendations are immutable after submission; any change creates a new revision with a full audit trail.'],
    ['h1','APIs'],
    ['tbl',['Method + Path','Purpose'],[
      ['GET  /api/award/recommendation/{rfqId}','Award recommendation packet'],
      ['POST /api/award/submit','Submit award decision'],
      ['POST /api/award/override','Record override + justification'],
      ['GET  /api/award/scenarios','Load / save what-if scenarios'],
      ['GET  /api/approval/matrix','Live approval matrix'],
      ['POST /api/report/executive-summary','Generate one-page executive summary'],
    ],[42,58]],
    ['h1','Database tables'],
    ['ul',['AwardRecommendation','AwardScenario','AwardApproval','AwardOverride','SupplierRanking','CostOwnership','ApprovalWorkflow','AuditLog']],
    ['h1','KPIs'],
    ['ul',['AI Recommendation Acceptance Rate','Average Procurement Savings','Total Cost of Ownership Savings','Award Cycle Time','Override Rate','Supplier Concentration Index','Procurement Risk Score']],
    ['h1','Acceptance criteria'],
    ['ul',[
      'Supplier rankings are calculated from configurable weighted criteria.',
      'Total Cost of Ownership is included in every recommendation.',
      'Scenario simulations do not modify live procurement data.',
      'Any override requires a reason and is permanently audited.',
      'The selected supplier automatically advances to Purchase Order generation after all required approvals.',
      'A one-page executive summary can be generated for every award decision.',
    ]],
    ['note','Enhancement — Corporate Procurement Memory','Beyond a single procurement, Nexi should remember how previous award decisions performed. For every awarded supplier she tracks: Did they deliver on time? Did final cost match the quotation? Were there quality issues? How many warranty claims? How many change orders? Was the buyer satisfied? Over time she recommends based on actual business outcomes, not just on quotations.'],
  ]
};

// Screen 009 — Purchase Order Generation
const S009 = { n:'009', docId:'ACC-PUR-009', title:'Purchase Order Generation',
  subtitle:'Official company obligation — extreme control required',
  sections:[
    ['h1','Purpose'],
    ['p','Generate the official Purchase Order (PO) from the approved supplier award. The PO is generated automatically from approved data. Users should never retype information that already exists in the PR, RFQ, quotation, or award recommendation.'],
    ['h1','Entry conditions'],
    ['ul',['Award approved','Budget approved','Approval workflow completed','Supplier selected','No blocking compliance issues']],
    ['h1','Purchase Order number'],
    ['code','PO-YYYY-NNNNNN   (example: PO-2026-001254)'],
    ['p','Sequential · company configurable · immutable after creation.'],
    ['h1','Header'],
    ['ul',['PO Number','Supplier','Purchase Request','RFQ','Award Reference','Buyer','Department','Project','Cost Center','Currency','Issue Date','Required Delivery Date','PO Status']],
    ['h1','Status workflow'],
    ['flow',['Draft','Pending Approval (if amendment)','Issued','Supplier Acknowledged','Partially Delivered','Fully Delivered','Closed','Archived']],
    ['h1','Supplier information (auto-filled)'],
    ['ul',['Company Name','Address','Contact Person','Email','Telephone','Tax ID','Payment Terms','Delivery Terms','Incoterms','Bank Details (view restricted)']],
    ['h1','Item grid'],
    ['ul',['Line Number','Item Code','Description','Technical Specification Reference','Quantity','Unit','Unit Price','Discount','Tax','Freight Allocation','Line Total','Delivery Date','Delivery Location','Warehouse','Remarks']],
    ['p','Every field is inherited from approved procurement documents unless explicitly editable.'],
    ['h1','Financial summary'],
    ['ul',['Subtotal','Discount','Tax','Shipping','Insurance','Other Charges','Grand Total','Budget Remaining','Commitment Amount','Accounting GL Preview']],
    ['h1','Attachments (auto-attached)'],
    ['ul',['Approved Purchase Request','RFQ','Final Supplier Quotation','Award Recommendation','Technical Drawings','Specifications','Contract (if applicable)']],
    ['p','No manual searching required.'],
    ['h1','Purchase terms'],
    ['ul',['Payment Terms','Delivery Terms','Warranty','Penalty Clauses','Quality Requirements','Inspection Requirements','Packing Requirements','Required Documentation','Insurance Requirements','Acceptance Criteria']],
    ['h1','Delivery schedule'],
    ['p','Supports Single · Partial · Milestone · Scheduled Delivery. Each delivery has: Date · Quantity · Destination · Warehouse · Responsible Receiver.'],
    ['h1','Compliance verification (before issue)'],
    ['ul',['Supplier active','Required approvals completed','Budget still available','Certifications valid','Insurance valid','Contract valid','Sanctions / blacklist checks (if enabled)','Required attachments present']],
    ['p','If any mandatory rule fails, PO issuance is blocked.'],
    ['h1','Supplier confirmation'],
    ['p','Supplier receives the PO via Email · Supplier Portal · EDI/API (optional). Supplier options: Accept · Reject · Request Amendment · Propose Delivery Change. Every response tracked.'],
    ['h1','PO amendments'],
    ['p','A new revision is created. Original PO remains immutable. Every amendment records: revision number · date · user · reason · approval (if required) · supplier acknowledgment.'],
    ['h1','Integration (after issue)'],
    ['ul',['Commit budget in Accounting','Create PO in SOS Inventory','Notify Warehouse','Notify Requester','Notify Finance (if configured)','Start delivery tracking']],
    ['h1','User actions'],
    ['ul',['Generate PO','Preview','Validate','Issue','Print PDF','Email Supplier','Export PDF','Export Excel','Create Amendment','Cancel (before issue only)']],
    ['h1','Security'],
    ['p','Only authorized Purchasing users can issue a PO. Only authorized approvers can approve amendments. Original PO cannot be edited after issue. Digital signatures supported. Every action written to the audit log.'],
    ['h1','APIs'],
    ['tbl',['Method + Path','Purpose'],[
      ['POST /api/purchase-orders/create','Create PO from approved award'],
      ['POST /api/purchase-orders/issue','Issue PO (validate + commit)'],
      ['POST /api/purchase-orders/amend','Create amendment'],
      ['GET  /api/purchase-orders/{id}','Fetch PO'],
      ['POST /api/purchase-orders/send','Dispatch to supplier'],
      ['POST /api/sos/purchase-order','Push PO into SOS'],
      ['POST /api/accounting/commit-budget','Reserve budget commitment'],
    ],[42,58]],
    ['h1','Database tables'],
    ['ul',['PurchaseOrder','PurchaseOrderItems','PurchaseOrderRevisions','PurchaseOrderAttachments','PurchaseOrderTerms','PurchaseOrderDeliverySchedule','PurchaseOrderAcknowledgement','BudgetCommitments','AuditLog']],
    ['h1','Notifications'],
    ['ul',['On PO issue: Supplier · Requester · Purchasing Manager · Warehouse · Accounting · Finance (optional)','On supplier acknowledgment: Assigned Buyer · Purchasing Manager','On amendment request: Assigned Buyer · Purchasing Manager · Approvers (if required)']],
    ['h1','KPIs'],
    ['ul',['PO Cycle Time','Average Time from Award to PO','Supplier Acknowledgment Time','Amendment Rate','Budget Commitment Accuracy','On-Time PO Issuance']],
    ['h1','Acceptance criteria'],
    ['ul',[
      'PO data is generated from approved records without manual re-entry.',
      'Mandatory validations are completed before issue.',
      'Issued POs are immutable; changes require controlled amendments.',
      'Supplier acknowledgments are tracked and linked to the PO.',
      'Budget commitments and SOS integration occur automatically upon issue.',
      'All actions and revisions are fully auditable.',
    ]],
    ['note','Enhancement — Intelligent Purchase Order','The PO becomes a live operational object that continuously monitors: supplier acknowledgment status · delivery milestones · shipment delays · budget impact · contract compliance · upcoming receiving activities. If a supplier misses a milestone or requests a delivery change, Nexi immediately alerts Purchasing and updates the operational timeline.'],
  ]
};

// Screen 010 — Goods Receiving Center
const S010 = { n:'010', docId:'ACC-PUR-010', title:'Goods Receiving Center (GRN)',
  subtitle:'Supplier delivery → warehouse acceptance → quality inspection → inventory posting',
  sections:[
    ['h1','Purpose'],
    ['p','Manage the complete receiving process from supplier delivery through warehouse acceptance, quality inspection, inventory posting, and financial matching.'],
    ['note','Important principle','Receiving does NOT automatically mean acceptance. Goods can be: Accepted · Partially Accepted · Rejected · Quarantined · Returned.'],
    ['h1','Entry conditions'],
    ['ul',['Purchase Order Issued','Supplier Delivery Scheduled','Supplier Shipment Notice Received (Optional)']],
    ['h1','Layout — three panels'],
    ['h2','Left panel — incoming deliveries'],
    ['ul',['Expected Today','Expected Tomorrow','Overdue Deliveries','Deliveries Waiting Inspection','Partial Deliveries','Urgent Deliveries']],
    ['p','Selecting one opens the receiving workspace.'],
    ['h2','Center panel — delivery details header'],
    ['ul',['Receiving Number (GRN-YYYY-NNNNNN)','Purchase Order','Supplier','Truck Number','Driver','Receiving Warehouse','Receiving Date','Receiver','Delivery Status']],
    ['h2','Item receiving grid'],
    ['ul',['Item Code','Description','Ordered Qty','Delivered Qty','Accepted Qty','Rejected Qty','Remaining Qty','Unit','Batch Number','Serial Number','Expiry Date (if applicable)','Warehouse Location','Inspection Status','Remarks']],
    ['h1','Barcode / QR / RFID'],
    ['p','Each line supports Barcode Scan · QR Scan · RFID Scan · Manual Entry (permission controlled). After scanning, system validates: correct item · correct PO · correct quantity · duplicate scan · wrong warehouse.'],
    ['h1','Photo documentation'],
    ['p','Receiver may attach: photos · videos · documents · damage reports · packing lists · delivery receipts. Every file becomes part of the permanent receiving record.'],
    ['h1','Quantity validation'],
    ['tbl',['Field','Example'],[
      ['Ordered','100'],['Received Previously','30'],['Delivered Today','50'],['Remaining','20'],
    ],[35,65]],
    ['h1','Over-delivery / under-delivery'],
    ['ul',['Over-delivery: system displays Over Delivery flag, Approval Required, configurable company policy (Accept · Reject · Partial Accept)','Under-delivery: system calculates Outstanding Balance · Expected Date · Back Order · Supplier Commitment']],
    ['h1','Quality inspection'],
    ['flow',['Pending Inspection','Passed','Accepted']],
    ['flow',['Failed','Quarantine','Return to Supplier']],
    ['h2','Inspection checklist'],
    ['ul',['Visual Inspection','Packaging','Label Verification','Specification Match','Damage','Dimensions','Certificates','Temperature','Batch Verification','Expiry Verification','Custom Checklist']],
    ['h1','Warehouse posting'],
    ['p','Only after acceptance. Automatically updates: SOS Inventory · Warehouse Stock · Available Stock · Reserved Stock · Inventory Valuation · Lot Tracking · Serial Numbers.'],
    ['h1','Right panel — Nexi receiving assistant'],
    ['ul',['Expected Quantity','Supplier History','Past Defects','Recommended Inspection Level','Risk Score','Delivery Performance','Warranty Alerts','Special Instructions']],
    ['h1','AI receiving analysis'],
    ['ul',['Frequent Supplier Short Deliveries','Repeated Damages','Wrong Packaging','Repeated Batch Problems','Late Deliveries','Temperature Deviations','Unexpected Serial Numbers','Repeated Quality Issues']],
    ['h1','Exceptions'],
    ['ul',['Damage','Missing Items','Wrong Items','Incorrect Quantity','Expired Products','Failed Inspection','Broken Packaging','Missing Documentation','Wrong Batch','Wrong Serial Number']],
    ['p','Every exception creates an incident record.'],
    ['h1','Return to Supplier (RTS)'],
    ['p','If rejected, automatically prepares: Return Authorization · Supplier Notification · Return Items · Reason · Photos · Replacement Request · Credit Request · Replacement Deadline.'],
    ['h1','Financial matching — three-way match'],
    ['flow',['Purchase Order','Goods Received','Supplier Invoice']],
    ['p','Only matching transactions proceed to payment unless an authorized exception is approved.'],
    ['h1','User actions'],
    ['ul',['Receive','Scan','Accept','Reject','Partial Accept','Quarantine','Return','Transfer','Print GRN','Generate Incident','Upload Photos']],
    ['h1','Security'],
    ['p','Warehouse cannot modify PO prices. Accounting cannot modify received quantities. Quality can only change inspection status. Only Purchasing can authorize supplier-related exceptions. Every action requires authentication and is audited.'],
    ['h1','APIs'],
    ['tbl',['Method + Path','Purpose'],[
      ['POST /api/grn/create','Create GRN header'],
      ['POST /api/grn/receive','Record received quantities'],
      ['POST /api/grn/inspection','Record inspection results'],
      ['POST /api/grn/accept','Accept quantities into stock'],
      ['POST /api/grn/reject','Reject quantities'],
      ['POST /api/grn/return','Create Return to Supplier'],
      ['POST /api/sos/inventory/receive','Push accepted stock into SOS'],
      ['GET  /api/po/{id}','PO context'],
      ['GET  /api/supplier/history','Supplier history for assistant panel'],
      ['POST /api/photos/upload','Photo / evidence upload'],
    ],[42,58]],
    ['h1','Database tables'],
    ['ul',['GoodsReceipt','GoodsReceiptItems','InspectionResults','InspectionChecklist','Returns','WarehouseTransactions','InventoryLots','InventorySerials','ReceivingPhotos','ReceivingIncidents','AuditLog']],
    ['h1','Notifications'],
    ['ul',['Receiving Completed','Inspection Failed','Return Created','Supplier Replacement Required','Warehouse Updated','Accounting Ready for Invoice Matching','Purchasing Exception Required']],
    ['h1','KPIs'],
    ['ul',['Receiving Accuracy','Average Receiving Time','Inspection Pass Rate','Supplier Defect Rate','Supplier Short Delivery Rate','Average Time to Stock Availability','Return Rate','Three-Way Match Success Rate']],
    ['h1','Acceptance criteria'],
    ['ul',[
      'Goods cannot be received against an invalid or closed PO.',
      'Quantity validations prevent unauthorized over-receiving unless approved by policy.',
      'Inventory is updated only after accepted quantities are confirmed.',
      'Inspection results determine inventory availability (Accepted vs. Quarantine).',
      'All receiving exceptions generate traceable incident records.',
      'Every receiving transaction is linked to the originating PO and fully audited.',
    ]],
    ['note','Enhancement — Intelligent Receiving','When a shipment arrives, Nexi analyses: supplier defect rate · delivery punctuality · shipment value · product criticality · regulatory requirements · past inspection failures. She dynamically recommends the inspection level: L1 Visual · L2 Random sampling · L3 Full quality inspection · L4 Mandatory laboratory / engineering verification before inventory release.'],
  ]
};

// Screen 011 — Invoice Verification & Three-Way Matching
const S011 = { n:'011', docId:'ACC-PUR-011', title:'Invoice Verification & Three-Way Matching',
  subtitle:'Protect the company from overbilling, duplicates, fraud',
  sections:[
    ['h1','Purpose'],
    ['p','Verify supplier invoices against Purchase Order · Goods Receipt (GRN) · Supplier Invoice. No invoice proceeds to payment unless company rules are satisfied.'],
    ['p','Protects the company from: overbilling · duplicate invoices · incorrect quantities · incorrect prices · fraud · payment mistakes.'],
    ['h1','Entry conditions'],
    ['ul',['Goods Received','Supplier Invoice Received','Purchase Order Exists']],
    ['h1','Header'],
    ['ul',['Invoice Number','Supplier','PO Number','GRN Number','Invoice Date','Due Date','Currency','Invoice Status','Assigned Accountant','Assigned Buyer']],
    ['h1','Status workflow'],
    ['flow',['Invoice Received','OCR Processing','AI Validation','Three-Way Match','Exception Review (if required)','Approved','Payment Queue','Paid','Closed']],
    ['h1','Left panel — invoice information'],
    ['ul',['Invoice Amount','Supplier','Purchase Order','Delivery','Tax','Payment Terms','Invoice Currency','Exchange Rate','Attachments']],
    ['h1','Invoice attachments'],
    ['ul',['PDF','XML','Images','Scanned Documents','Government e-Invoice (future)']],
    ['h1','Center panel — three-way matching'],
    ['tbl',['Field','PO','GRN','Invoice','Status'],[
      ['Item','✔','✔','✔','Match'],
      ['Quantity','100','100','100','Match'],
      ['Unit Price','₱120','₱120','₱120','Match'],
      ['Tax','12%','12%','12%','Match'],
      ['Freight','₱2,000','₱2,000','₱2,000','Match'],
    ],[24,19,19,19,19]],
    ['p','Every discrepancy is highlighted.'],
    ['h1','Matching rules'],
    ['p','Exact Match · Tolerance Match · Manual Review. Company configurable. Example — Quantity tolerance ±2% · Price tolerance ±1% · Tax 0%.'],
    ['h1','AI invoice reading'],
    ['p','Automatically extracts: Supplier · Invoice Number · Invoice Date · Items · Prices · Taxes · Discounts · Payment Terms · Bank Details · Reference Numbers. No manual encoding.'],
    ['h1','Duplicate invoice detection'],
    ['p','Checks: Invoice Number · Supplier · Amount · Date · PO · GRN · Historical Payments. If duplicate suspected, payment blocked.'],
    ['h1','Right panel — Nexi financial assistant'],
    ['ul',['Invoice Risk','Payment Risk','Budget Impact','Duplicate Probability','Recommended Action','Confidence']],
    ['p','Example — Invoice matches 99.7% · Duplicate Risk 0% · Recommendation: Approve.'],
    ['h1','Exceptions'],
    ['ul',['Price Difference','Quantity Difference','Tax Difference','Freight Difference','Missing GRN','Missing PO','Expired PO','Closed PO','Incorrect Currency','Wrong Supplier']],
    ['h2','Exception resolution'],
    ['p','Assign to Purchasing · Accounting · Warehouse · Supplier · Engineering · Legal. Each exception receives Owner · Priority · Deadline · Status.'],
    ['h1','Payment readiness'],
    ['ul',['Approved','Waiting Approval','Blocked','Pending Exception','Ready for Payment']],
    ['h1','Invoice timeline'],
    ['flow',['Invoice Received','OCR Complete','Three-Way Match','Approved','Payment Scheduled','Paid']],
    ['h1','Payment information'],
    ['ul',['Payment Terms','Due Date','Discount Date','Early Payment Discount','Penalty Date','Bank Account','Payment Method']],
    ['h1','Fraud detection'],
    ['ul',['Duplicate invoices','Changed bank accounts','Repeated invoice numbers','Abnormal invoice values','Invoice splitting','Suspicious tax','Repeated supplier corrections','Invoice timing anomalies']],
    ['h1','Buyer / accountant actions'],
    ['ul',['Approve','Reject','Request Supplier Correction','Escalate','Add Comment','Assign Exception','Export Report','Print']],
    ['h1','Security'],
    ['p','Only Accounting approves invoices. Purchasing can review commercial discrepancies. Warehouse cannot approve invoices. Bank account changes require dual approval. Every financial change is audited.'],
    ['h1','APIs'],
    ['tbl',['Method + Path','Purpose'],[
      ['POST /api/invoice/upload','Upload invoice file'],
      ['POST /api/invoice/ocr','OCR + extract'],
      ['GET  /api/invoice/match','Three-way match result'],
      ['POST /api/invoice/approve','Approve invoice'],
      ['POST /api/invoice/reject','Reject invoice'],
      ['GET  /api/payment/status','Payment queue status'],
      ['POST /api/fraud/check','Run fraud checks'],
    ],[42,58]],
    ['h1','Database tables'],
    ['ul',['Invoices','InvoiceItems','InvoiceMatching','InvoiceExceptions','InvoiceApprovals','PaymentSchedule','SupplierBankAccounts','FraudAlerts','AuditLog']],
    ['h1','Notifications'],
    ['ul',['Invoice Received','Matching Failed','Invoice Approved','Payment Ready','Duplicate Invoice Alert','Supplier Correction Requested']],
    ['h1','KPIs'],
    ['ul',['Invoice Match Rate','Average Invoice Approval Time','Duplicate Invoice Prevention','Early Payment Discount Captured','Invoice Exception Rate','Average Payment Cycle','Fraud Alerts Generated']],
    ['h1','Acceptance criteria'],
    ['ul',[
      'Every invoice is automatically matched against the PO and GRN.',
      'OCR extracts invoice data with confidence scoring; low-confidence fields flagged for review.',
      'Duplicate invoice detection blocks payment until resolved.',
      'Tolerance rules are configurable by company policy.',
      'Invoice approval follows role-based permissions.',
      'All financial decisions and exceptions are fully audited.',
      'Approved invoices move automatically to the Accounts Payable payment process.',
    ]],
    ['note','Enhancement — Autonomous Financial Validation','Nexi calculates a Financial Confidence Score (0-100) per invoice — PO Match · GRN Match · Supplier History · Pricing Consistency · Duplicate Risk · Bank Account Verified · Invoice Pattern Normal. Policy can then define: 95-100 auto-route for Accounting approval · 80-94 require Purchasing review · <80 block payment and create investigation task. Human decides — Nexi assists.'],
  ]
};

// Screen 012 — Supplier Performance & Scorecard
const S012 = { n:'012', docId:'ACC-PUR-012', title:'Supplier Performance & Scorecard',
  subtitle:'Suppliers become continuously evaluated business partners',
  sections:[
    ['h1','Purpose'],
    ['p','This screen transforms suppliers from static records into continuously evaluated business partners. Every PO, delivery, GRN, quality inspection, invoice, negotiation and contract automatically updates the supplier\'s performance score.'],
    ['p','The score is system-generated. Users may add comments but cannot manually inflate supplier ratings.'],
    ['h1','Objectives'],
    ['ul',['Provide management with objective supplier performance','Support future purchasing decisions','Identify preferred suppliers','Detect supplier deterioration before it becomes a business problem']],
    ['h1','Entry conditions'],
    ['p','Available after at least one completed Purchase Order.'],
    ['h1','Layout — three-column dashboard'],
    ['h2','Left panel — supplier directory'],
    ['ul',['Supplier Name','Overall Score','Status','Preferred Supplier','Conditional Supplier','Suspended','Blacklisted']],
    ['p','Search / filter by: Category · Country · Risk · Buyer · Product Category.'],
    ['h2','Center panel — Supplier 360°'],
    ['p','Overall Score 0-100 displayed as a circular gauge. Example: 96.4.'],
    ['h2','Performance breakdown'],
    ['ul',['Quality','Delivery','Price Stability','Commercial Performance','Communication','Warranty Support','Technical Support','Invoice Accuracy','Contract Compliance','Sustainability']],
    ['p','Each receives an individual score.'],
    ['h2','Trend'],
    ['p','Last 30 days · 90 days · 12 months · 3 years. Shows improving or declining performance.'],
    ['h2','Right panel — Nexi supplier intelligence'],
    ['ul',['Supplier Risk','Expected Performance','Future Capacity','Recommended Action','Preferred Supplier · Conditional Supplier · Suspend Supplier · Increase Business · Reduce Business · Review Required']],
    ['h1','Automatic KPI calculation'],
    ['h3','Delivery'],
    ['ul',['On-Time Delivery %','Average Delay','Average Early Delivery','Emergency Deliveries','Missed Deliveries']],
    ['h3','Quality'],
    ['ul',['Accepted Deliveries','Rejected Deliveries','Inspection Failures','Defect Rate','Replacement Time','Warranty Claims','Corrective Actions']],
    ['h3','Commercial'],
    ['ul',['Average Price','Price Stability','Negotiation Success','Discount History','Cost Savings Generated','Contract Compliance']],
    ['h3','Communication'],
    ['ul',['Average Response Time','Average RFQ Response','Negotiation Response','Issue Resolution Time']],
    ['h3','Financial'],
    ['ul',['Invoice Accuracy','Credit Note Accuracy','Payment Disputes','Bank Change Requests','Financial Risk']],
    ['h3','Sustainability (configurable)'],
    ['ul',['Environmental Certifications','Ethical Compliance','Carbon Initiatives','Waste Management']],
    ['h1','AI risk prediction'],
    ['ul',['Likelihood of Late Delivery','Likelihood of Quality Failure','Financial Instability','Supplier Capacity Constraints','Price Increase Probability','Supply Chain Risk','Supplier Dependency']],
    ['p','Risk levels: Low · Medium · High · Critical.'],
    ['h1','Performance timeline'],
    ['p','Chronological history of: POs · Deliveries · Returns · Quality Incidents · Negotiations · Contracts · Invoices · Corrective Actions · Audits. Every event clickable.'],
    ['h1','Supplier Improvement Plan'],
    ['p','When a supplier falls below a configurable threshold, Nexi creates an improvement plan.'],
    ['tbl',['Field','Value'],[
      ['Issue','Late Deliveries'],['Target','95% On-Time'],
      ['Review Date','30 Days'],['Owner','Purchasing Manager / Supplier Representative'],
      ['Progress','Automatically tracked'],
    ],[25,75]],
    ['h1','Preferred Supplier logic (example thresholds)'],
    ['ul',['Overall Score ≥ 90','Quality ≥ 95','Delivery ≥ 95','Risk = Low','No major non-conformance in last 12 months → Preferred Supplier']],
    ['p','If the supplier falls below policy thresholds, Nexi automatically recommends a review.'],
    ['h1','Blacklist management'],
    ['p','Only authorized management may suspend or blacklist suppliers. Reasons include: repeated quality failures · fraud · compliance violations · contract breaches · safety violations · legal issues. Every blacklist action requires approval and justification.'],
    ['h1','Buyer / Manager actions'],
    ['ul',['View Supplier','Compare Suppliers','View Purchase History','View Contracts','Start Corrective Action','Schedule Supplier Audit','Create Improvement Plan','Recommend Preferred Supplier','Recommend Suspension','Export Scorecard']],
    ['h1','Security'],
    ['p','Performance metrics are system-generated. Manual changes not permitted. Management actions require role-based approval. Every action audited.'],
    ['h1','APIs'],
    ['tbl',['Method + Path','Purpose'],[
      ['GET  /api/suppliers/scorecard','Overall + breakdown scores'],
      ['GET  /api/suppliers/performance','KPI panel'],
      ['GET  /api/suppliers/timeline','Chronological history'],
      ['GET  /api/suppliers/risk','Risk prediction'],
      ['POST /api/suppliers/improvement-plan','Create improvement plan'],
      ['POST /api/suppliers/status','Change status (with approval)'],
    ],[42,58]],
    ['h1','Database tables'],
    ['ul',['SupplierPerformance','SupplierKPIs','SupplierRisk','SupplierImprovementPlans','SupplierStatusHistory','SupplierAudits','CorrectiveActions','SupplierTimeline','AuditLog']],
    ['h1','KPIs'],
    ['ul',['Overall Supplier Score','On-Time Delivery','Quality Acceptance Rate','Average Negotiation Savings','Average Response Time','Invoice Accuracy','Warranty Claim Rate','Supplier Risk Index','Preferred Supplier Ratio','Supplier Improvement Success Rate']],
    ['h1','Acceptance criteria'],
    ['ul',[
      'Every completed procurement transaction automatically updates supplier KPIs.',
      'Overall supplier scores are calculated from configurable weighting rules.',
      'Historical trends are retained for long-term analysis.',
      'Improvement plans can be tracked through completion.',
      'Preferred and suspended supplier status changes require authorization and are fully audited.',
      'Future purchasing decisions can reference the current supplier score and risk level without manual intervention.',
    ]],
    ['note','Enhancement — Supplier Capacity Intelligence','Before issuing a large RFQ or PO, Nexi estimates whether the supplier can realistically fulfill the demand by considering: historical fulfillment rates · current open POs · seasonal demand patterns · manufacturing lead times · production capacity (where available) · existing commitments to HydroNexis. Answers "Can this supplier successfully deliver this order now?"'],
  ]
};

// Screen 013 — Procurement Analytics & Executive Intelligence
const S013 = { n:'013', docId:'ACC-PUR-013', title:'Procurement Analytics & Executive Intelligence',
  subtitle:'Executive Decision Center — read-only for most users',
  sections:[
    ['h1','Purpose'],
    ['p','Provide executives with complete visibility into procurement performance, costs, supplier health, risks, savings, and future purchasing requirements. This screen is read-only for most users. No operational work is performed here. It is an Executive Decision Center.'],
    ['h1','Users'],
    ['tbl',['Role','Access'],[
      ['CEO','Full'],['President','Full'],['CFO','Full'],['Accounting Manager','Full'],['Purchasing Manager','Full'],
      ['Department Managers','Limited'],['Buyers','Personal KPIs only'],
    ],[45,55]],
    ['h1','Dashboard layout'],
    ['p','Four-row executive dashboard. No scrolling on a 32-inch monitor. Every widget drill-down capable.'],
    ['h1','Executive KPI row — Procurement spend'],
    ['ul',['Today','This Month','This Year','Budget','Forecast']],
    ['h2','Savings'],
    ['ul',['Negotiation Savings','Contract Savings','Inventory Transfer Savings','AI Savings','Emergency Purchase Avoidance']],
    ['h2','Purchase cycle'],
    ['ul',['Average PR Approval Time','Average RFQ Time','Average Negotiation Time','Average PO Generation','Average Receiving Time','Average Invoice Approval','End-to-End Procurement Cycle']],
    ['h2','Procurement Health Score'],
    ['p','Overall Score 0-100 calculated from Supplier Performance · Budget Compliance · Cycle Time · Risk · Savings · Quality.'],
    ['h1','Spend analytics'],
    ['p','Interactive charts. Spend by: Supplier · Category · Department · Project · Warehouse · Region · Buyer · Month · Quarter · Year. Every chart supports drill-down.'],
    ['h1','Budget intelligence'],
    ['ul',['Approved Budget','Committed Budget','Actual Spend','Forecast Spend','Remaining Budget','Over Budget Projects','Department Utilization','Cash Flow Forecast']],
    ['h1','Supplier intelligence'],
    ['ul',['Top Suppliers','Highest Risk Suppliers','Most Improved Suppliers','Suppliers Needing Review','Preferred Suppliers','Blacklisted Suppliers','Supplier Dependency','Supplier Concentration']],
    ['h1','Procurement risk map'],
    ['p','Heat map. Categories: Supplier Risk · Budget Risk · Delivery Risk · Contract Risk · Compliance Risk · Currency Risk · Single Source Risk · Inventory Risk. Each area clickable.'],
    ['h1','AI insights (examples)'],
    ['ul',[
      'Purchasing costs increased 8% compared with last month.',
      'Supplier ABC has delivered late five consecutive times.',
      'Annual contract renewal due in 21 days.',
      'Combining three purchase requests will save approximately ₱425,000.',
      'Switching to Supplier XYZ could reduce annual cost by 12%.',
    ]],
    ['p','Every insight links directly to supporting transactions.'],
    ['h1','Procurement forecast'],
    ['ul',['Future Spend','Supplier Capacity','Budget Exhaustion','Contract Expiration','Inventory Shortages','Price Trends','Demand Peaks','Cash Requirements']],
    ['p','Forecast periods: 30 Days · 90 Days · 12 Months · 3 Years.'],
    ['h1','Executive alerts (critical only)'],
    ['ul',['Budget Exceeded','Supplier Bankruptcy Risk','Repeated Quality Failures','Contract Expiration','Late Deliveries','Single Supplier Dependency','Compliance Failure','Fraud Investigation','Approval Bottlenecks']],
    ['h1','Executive drill down'],
    ['p','Every KPI opens Supplier · Purchase Order · Project · Buyer · Department · Invoice · Contract · Timeline. No separate search required.'],
    ['h1','Benchmarking'],
    ['ul',['This Month vs Last Month','This Quarter vs Previous Quarter','This Year vs Previous Year','Company vs Target','Department vs Department','Buyer vs Buyer']],
    ['h1','AI executive recommendations — Top 10 opportunities'],
    ['ul',['Reduce Spend','Improve Supplier Mix','Renegotiate Contracts','Increase Inventory Transfers','Reduce Emergency Purchases','Consolidate Suppliers','Improve Payment Terms','Extend Contracts','Increase Competition','Reduce Procurement Cycle']],
    ['p','Every recommendation includes estimated annual financial impact.'],
    ['h1','Export'],
    ['ul',['PDF','Excel','PowerPoint','Executive Board Pack','Monthly Procurement Report','Quarterly Report','Annual Report']],
    ['h1','Security'],
    ['p','Executives view all data. Managers view assigned departments. Buyers view only their procurement activities. Financial values follow role-based permissions. Every report export is logged.'],
    ['h1','APIs'],
    ['tbl',['Method + Path','Purpose'],[
      ['GET  /api/analytics/procurement','Overall procurement KPIs'],
      ['GET  /api/analytics/spend','Spend by dimension'],
      ['GET  /api/analytics/suppliers','Supplier analytics'],
      ['GET  /api/analytics/budget','Budget analytics'],
      ['GET  /api/analytics/risk','Risk heat map'],
      ['GET  /api/analytics/forecast','Forecast payloads'],
      ['GET  /api/analytics/insights','AI insight feed'],
      ['POST /api/report/export','Export report (PDF / Excel / PPTX)'],
    ],[42,58]],
    ['h1','Database tables'],
    ['ul',['AnalyticsCache','ProcurementKPIs','ExecutiveInsights','ForecastData','RiskDashboard','SpendAnalytics','SupplierAnalytics','BudgetAnalytics','AuditLog']],
    ['h1','KPIs'],
    ['ul',['Total Spend','Annual Savings','Negotiation Savings','Average Procurement Cycle','Budget Compliance','Supplier Performance Index','Contract Utilization','Procurement ROI','Emergency Purchase Rate','AI Recommendation Adoption Rate']],
    ['h1','Acceptance criteria'],
    ['ul',[
      'Dashboard loads in under 5 seconds using pre-aggregated analytics where appropriate.',
      'Every KPI supports drill-down to the underlying transactions.',
      'Forecasts are recalculated on configurable schedules.',
      'AI insights are traceable to supporting procurement data.',
      'Executive exports reproduce the dashboard accurately.',
      'All financial data respects role-based security and audit requirements.',
    ]],
    ['note','Enhancement — Executive Procurement Digital Twin','Nexi creates a live simulation of the procurement operation. Executives test scenarios like "What if Supplier A raises prices by 15%?" · "What if we consolidate into three annual contracts?" · "What if we reduce emergency purchasing by 50%?" · "What if we shift 20% of spend to local suppliers?" · "What if demand rises 30% next quarter?" The system immediately projects impacts on cash flow · budget · procurement cycle time · supplier workload · inventory · operational risk · estimated annual savings.'],
  ]
};

return { INDEX, screens: [S001,S002,S003,S004,S005,S006,S007,S008,S009,S010,S011,S012,S013] };

})();
